featurehub-io/featurehub

- admin-frontend/app_singleapp/lib/api/client_api.dart
- admin-frontend/app_singleapp/lib/widgets/user/signin/signin_widget.dart
- backend/mr-db-sql/src/main/java/io/featurehub/db/services/AuthenticationSqlApi.java
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/AuthenticationSpec.groovy
When login occurs, the Acls are not passed back. This fixes this issue, and ensures that all of the application level roles
are immediately available to a user. 
In the process was also discovered a double login call, which has also been addressed.
Fixes #119
Manual front end testing. Integration test in back end.
Without fix:
(1) start front end app in IDE
(2) login as superuser
(3) attempt to create a feature. This dialog will pop because you are superuser, but as you have no roles it will only show a cancel button.
During this process watch the network calls on login. There will be 3 - one OPTION and two to login.
> Login double call and permission issue bugfix

- sdks/typescript/client-typescript-eventsource/README.md
This separates the concepts into their different sections, not mixing them all up like before.
> rearrangement of typescript docs

- admin-frontend/app_singleapp/lib/widgets/features/environments_features_list_view.dart
- admin-frontend/app_singleapp/lib/widgets/features/feature_status_bloc.dart
- admin-frontend/app_singleapp/lib/widgets/features/hidden_environment_list.dart
- admin-frontend/app_singleapp/lib/widgets/features/tabs_bloc.dart
- backend/mr/src/main/java/io/featurehub/mr/resources/UserStateResource.java
Swapping around hidden for shown environments. By default only 1 environment is shown, and what is shown is 
persisted in user state in the backend. Users can still show all if they wish.
> support saving shown / hidden environments per application

- admin-frontend/app_singleapp/lib/routes/landing_route.dart
- admin-frontend/app_singleapp/lib/widgets/user/signin/signin_widget.dart
Resolved issue where typing the wrong password would
prevent you from logging in a second time with the right
password without page refresh.
Fixes #195
> Wrong password prevents correction

- admin-frontend/app_singleapp/lib/widgets/features/custom_strategy_bloc.dart
- backend/mr-api/mr-api.yaml
- backend/mr-db-api/src/main/java/io/featurehub/db/api/FeatureApi.java
- backend/mr-db-api/src/main/java/io/featurehub/db/api/RolloutStrategyValidator.java
- backend/mr-db-sql/src/main/java/io/featurehub/db/listener/FeatureUpdateBySDKApi.java
- backend/mr-db-sql/src/main/java/io/featurehub/db/listener/FeatureUpdateListener.java
- backend/mr-db-sql/src/main/java/io/featurehub/db/services/FeatureSqlApi.java
- backend/mr-db-sql/src/main/java/io/featurehub/db/services/strategies/RolloutStrategyValidationUtils.java
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureSpec.groovy
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/RolloutStrategyValidationUtilsSpec.groovy
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/StrategyDifferUtilsSpec.groovy
- backend/mr/src/main/java/io/featurehub/mr/resources/EnvironmentFeatureResource.java
- backend/mr/src/main/java/io/featurehub/mr/resources/FeatureResource.java
- backend/mr/src/main/java/io/featurehub/mr/resources/RolloutStrategyResource.java
- sdks/java/client-java-loadtest/src/main/java/io/featurehub/loadtest/LoadTest.java
This change modifies the validation logic to return all
of the individual errors that exist for validation for a
strategy. Only custom strategies are covered. Existing
apis are updated to return the 422 necessary.
Fixes #206 
> Add API for rollout strategies

- .github/workflows/adocs-build.yml
- doc-gen/Dockerfile
- doc-gen/action.yml
- doc-gen/entrypoint.sh
- doc-gen/pom.xml
- docs/architecture.adoc
- docs/developers.adoc
- docs/identity.adoc
- docs/index.adoc
- docs/installation.adoc
This swaps us to using Maven for asciidoc generation of the docs.featurehub.io site. The advantage is consistent build, being able to build locally and preview and easy addition of extensions to Asciidoctor without having to fuss about with Ruby.
> Attempt to use Maven to build asciidocs

- admin-frontend/app_singleapp/lib/widgets/features/table-collapsed-view/tooltip.dart
- admin-frontend/app_singleapp/lib/widgets/features/table-collapsed-view/value_cell.dart
- admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/individual_strategy_bloc.dart
- admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/strategies/edit_value_strategy_link_button.dart
- admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/strategies/split_rollout_button.dart
- admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/strategies/strategy_editing_widget.dart
- e2e/test/steps/PortfolioStepdefs.dart
New invalid line causes failure
If you create an invalid line in a strategy attribute
and it is a new strategy, then the backend is communicating
in such a way that the frontend can never understand. This
resolves this and cleans up the whole strategy editing
section in terms of rollout strategy state.
Fixed exploding tooltip
This was blowing up as well.
Required for 1.1.1 release
> Fix new invalid line error and tooltip exploding

- sdks/dart/client-dart-api/CHANGELOG.md
- sdks/dart/client-dart-api/pubspec.yaml
- sdks/dart/client-dart-sdk/CHANGELOG.md
- sdks/dart/client-dart-sdk/pubspec.yaml
- sdks/typescript/client-typescript-core/package.json
release of Dart and NPM because they needed their docs updated.
> Release sdk 1.1.1

- admin-frontend/app_singleapp/lib/routes/service_env_route.dart
- admin-frontend/app_singleapp/lib/widgets/common/copy_to_clipboard_html.dart
Fix copy to clipboard button which is not working on Firefox browsers. 
Fixes # (280)
Tested with Safari, Firefox and Chrome
> fix copy-to-clipboard for Firefox (issue 280).

- backend/mr-db-api/src/main/java/io/featurehub/db/api/ServiceAccountApi.java
- backend/mr/src/main/java/io/featurehub/mr/resources/ServiceAccountResource.java
The portfolio id was not being used to check for permissions
to service accounts, the service account key was and thus
this was preventing a non-SuperAdmin user from changing
service account permissions.
Closes issue #278
> incorrect key used for portfolio id

- .github/workflows/typescript-core-build.yml
- sdks/typescript/featurehub-eventsource-sdk/package.json
- sdks/typescript/featurehub-repository/package-lock.json
- sdks/typescript/featurehub-repository/package.json
It is important that the package.json for featurehub-repository releases both es6 and commonjs format. And the publish step was wrong for both, it needs to run build not tsc.
> package.json for featurehub-repository got nuked in rebase

- admin-frontend/build/build.sh
- backend/build.sh
- backend/dacha/src/main/java/io/featurehub/dacha/Application.java
- backend/sse-edge/src/main/java/io/featurehub/edge/Application.java
- pipeline/app-master-pipeline/cloudbuild.yaml
- pipeline/build/base_mr/Dockerfile
- pipeline/build/base_mr/default_site
This covers a few minor items that affect different areas:
- Dacha did not stop when NATS was not available. This affects
its ability to run in a cluster when NATS is taken down.
- Dacha was not logging its error so diagnosing the fault was
difficult
- upgraded the MR server base image to focal from bionic to
match party server
- expose the health service for MR in the nginx config
- updates the master pipeline for retries for greater reliability
> 1.3.1 maintenance release

- backend/dacha/src/main/java/io/featurehub/dacha/InMemoryCache.java
- backend/sse-edge-api/src/main/resources/sse-api.yaml
- doc-gen/pom.xml
- docs/analytics.adoc
- docs/developers.adoc
- docs/identity.adoc
- docs/index.adoc
- sdks/README.adoc
- sdks/java/client-java-core/README.adoc
- sdks/java/client-java-core/src/main/java/io/featurehub/client/FeatureHubConfig.java
- sdks/typescript/featurehub-javascript-client-sdk/README.md
This cleans up:
- the SDK URL -> API Key migration
- adds in the developer documentation for client side eval
- removes the outdated asciidoc plugin for generating docs and embeds the Google Analytics into the doc pages
> Updated docs

- sdks/typescript/featurehub-javascript-client-sdk/app/featurehub_eventsource.ts
This resolves the issue where strategies would not work
with the new client-js-sdk.
Fixes issue #373
> Regression in ClientJS Strategy Support

- admin-frontend/app_mr_layer/pom.xml
- backend/dacha-api/pom.xml
- backend/mr-api/pom.xml
- backend/mr-streaming-api/pom.xml
This moves us to 5.1.0 as per recommendations from OpenAPI.
Fixes #386
> Upgrade OpenAPI dependencies

- admin-frontend/app_mr_layer/pom.xml
- admin-frontend/app_singleapp/test/person_test.dart
There is a bug in the ChipsInput widget that is causing
deleted items to come back as if they were added. That will
be addressed in a different ticket. In this ticket, the
issue is that the "other" field in Person was causing the
equals method of Person to always fail, and thus the
list of members being forced into a Set would fail because
two people who were identical were appearing not to be. The
backend would rightfully reject this request.
Fixes issue #382
> Conflicting users being added in Groups causing explosions

- admin-frontend/app_singleapp/lib/routes/manage_group_route.dart
If you choose to Add a user and then remove them and then
add them again in the dialog, it will fail to remove them
from the list. Depends on the merge of #382
Fixes issue #390
> Not removing items from internal list for group/add member

- sdks/client-csharp/FeatureHubSDK/EventServiceListener.cs
- sdks/client-csharp/FeatureHubSDK/FeatureHubSDK.csproj
- sdks/client-csharp/FeatureHubSDK/README.md
The SDK has been updated with logging support for diagnosis,
and backoff has been disabled, as it was causing feature
drift.
> Update SDK with logging and disable backoff

- backend/common-web/src/main/kotlin/io/featurehub/health/MetricsHealthRegistration.kt
- backend/dacha/src/main/java/io/featurehub/dacha/Application.java
- backend/mr/src/main/java/io/featurehub/Application.java
- backend/mr/src/main/java/io/featurehub/mr/ManagementRepositoryFeature.java
- backend/party-server/src/main/java/io/featurehub/party/Application.java
- backend/sse-edge/src/main/java/io/featurehub/edge/Application.java
- docs/installation.adoc
Adds documentation and the functionality to expose all servers
on an alternative port for monitoring.
Fixes #399
> Allow the monitor port to be different from the app port

- sdks/typescript/featurehub-javascript-client-sdk/README.md
- sdks/typescript/featurehub-javascript-client-sdk/app/edge_featurehub_config.ts
- sdks/typescript/featurehub-javascript-client-sdk/package.json
- sdks/typescript/featurehub-javascript-client-sdk/test/feature_hub_config_spec.ts
When a url is provided with /features or /features/ at the end, the
SDK is supposed to strip it off and add it in its own format,
holding onto the base url for use in GET and PUT updates for the
test API. This was incorrectly formatting, so this adds a test
to ensure it is correct and fixes #411
> [typescript-client-sdk] Ensure if person passes url with /features it strips it correctly

- admin-frontend/app_singleapp/lib/version.dart
- admin-frontend/app_singleapp/lib/widgets/common/fh_appbar.dart
- admin-frontend/app_singleapp/lib/widgets/features/custom_strategy_bloc.dart
- admin-frontend/build-frontend.sh
- admin-frontend/build/build.sh
- admin-frontend/pom.xml
- admin-frontend/src/main/resources/post-build-assembly.xml
- admin-frontend/src/main/resources/pre-build-assembly.xml
- backend/common-web/src/main/kotlin/io/featurehub/info/InfoSource.kt
- backend/common-web/src/test/groovy/io/featurehub/info/InfoSourceSpec.groovy
- backend/common-web/src/test/resources/META-INF/MANIFEST.MF
- backend/tile-java/tile.xml
Changes the way the front end artifact is built so it is more friendly for ongoing development and isolated from "bad" changes. Exposes the version number from the Docker build to the front end and to the core application stack.
Fixes #380
> Ensure the Release Number is baked into apps

- backend/mr-api/common.yaml
- backend/mr-db-ebean/src/main/resources/dbmigration/h2/1.6.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/model/1.6.model.xml
- backend/mr-db-ebean/src/main/resources/dbmigration/mssql/1.6.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mysql/1.6.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/postgres/1.6.sql
- backend/mr-db-sql/src/main/java/io/featurehub/db/model/DbServiceAccount.java
Because the length of a service name was only
allowed to be 40 chars, when archiving added
the current timestamp this dropped to under 20.
This increases it to 100, with an API change
to allow for 70, giving the timestamp breather
space.
Fixes #448
> Service name length too short for archiving

- backend/mr-db-api/src/main/java/io/featurehub/db/api/PersonFeaturePermission.java
- backend/mr-db-sql/src/main/java/io/featurehub/db/services/FeatureSqlApi.java
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureSpec.groovy
the specific use case is where the feature
value does not exist and you have
lock/unlock role but not “set”. So you
are essentially creating the feature
value for the first time.
> Lock only perms not resolved correctly

- admin-frontend/app_mr_layer/pom.xml
- admin-frontend/app_mr_layer/pubspec.yaml
- backend/dacha-api/pom.xml
- backend/mr-api-java-server/pom.xml
- backend/mr-streaming-api/pom.xml
- backend/sse-edge-api/pom.xml
- backend/sse-edge-stats-api/pom.xml
- e2e/lib/user_common.dart
Update to 7.4 and fix the registration token url issue for the e2e tests.
> Update generator to latest Jersey OpenAPI generator

- sdks/typescript/featurehub-javascript-client-sdk/README.md
- sdks/typescript/featurehub-javascript-client-sdk/app/edge_featurehub_config.ts
- sdks/typescript/featurehub-javascript-client-sdk/package.json
- sdks/typescript/featurehub-javascript-client-sdk/test/feature_hub_config_spec.ts
- sdks/typescript/featurehub-javascript-node-sdk/package.json
The SSE client with recent changes was not correctly caching
the open connection and reusing it.
Fixes #488
> Resolve issue around not correctly caching Edge connection

- backend/common-web/src/main/kotlin/io/featurehub/health/CommonFeatureHubFeatures.kt
This allows support for the Immediate Scope annotation in Jersey which allows preloading of injection resources.
> Enable support for Immediate Scope

- admin-frontend/open_admin_app/lib/routes/create_user_route.dart
- admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/strategies/add_attribute_strategy_widget.dart
This appears to be a bug in the underlying framework,
but it resolves the issue where putting a recommended
const (recommended by the linting framework) on an
underlying stateful object prevents it from issuing a
didUpdateWidgets.
Fixes #494
> Const on Stateful object prevents didUpdateWidgets

- docs/installation.adoc
Update installation docs as our Options were a bit confusing. Now there is a clear separation on Evaluation, low-volume and Kubernetes deployments
> update installation options docs

- sdks/typescript/featurehub-javascript-client-sdk/app/strategy_matcher.ts
- sdks/typescript/featurehub-javascript-client-sdk/package.json
- sdks/typescript/featurehub-repository/app/strategy_matcher.ts
- sdks/typescript/featurehub-repository/package.json
Semver is fairly big and currently represents ~25% of featurehub-javascript-client-sdk. This change replaces `semver` with `semver-compare` is which tiny (<1kb). This change helps adoption of size-sensitive environments such as while serving webpages.
Although `semver` provides a compreensive way of comparing versions, current code [1] makes use of compare functions which ends up as a `SemVer.compare()` call without any extra options such as `includePrerelease`, `loose` and `rtl` (listed here [2]). That being said, current usage relies on `compareIdentifier` [3] which can be safely replaced by `semver-compare`'s compare function [4].
[1] https://github.com/featurehub-io/featurehub/blob/d49780e14a2b6b6fdad8c561e45d5a07f1844b34/sdks/typescript/featurehub-javascript-client-sdk/app/strategy_ma …
> Decreased javascript sdk size by replacing semver with semver-compare

- sdks/typescript/featurehub-javascript-client-sdk/app/context_impl.ts
- sdks/typescript/featurehub-javascript-client-sdk/test/client_context_spec.ts
The `LocalClientContext` allows passing an `Environment` object as the source for feature strategies. It decouples "serving" from "evaluation" which alows deployments can't use a Edge Service (e.g. due to amount of traffic). Such deployments should provide the Environment object using another strategy, such as serving a JSON file with a `Environment` object serialized.
Fixes #497
Added and run unittests.
> Introduced LocalClientContext for static deployments.

- backend/common-web/src/main/java/io/featurehub/jersey/config/CommonConfiguration.java
- backend/common-web/src/main/kotlin/io/featurehub/jersey/OffsetDateTimeQueryProvider.kt
- backend/composite-jersey/pom.xml
- backend/sse-edge-api/pom.xml
- backend/sse-edge-stats-api/async-api.yaml
- backend/sse-edge-stats-api/fake-api.yaml
- backend/sse-edge-stats-api/pom.xml
This allows support for Enums that are specifically matched to their OpenAPI counterparts and supports timestamps in query parameters.
> minor changes to config to allow for sdks to be held externally

- backend/dacha-api/dacha-api.yaml
- backend/dacha/src/main/java/io/featurehub/dacha/EnvironmentFeatures.java
- backend/dacha/src/main/java/io/featurehub/dacha/InMemoryCache.java
- backend/dacha/src/main/java/io/featurehub/dacha/InternalCache.java
- backend/dacha/src/main/kotlin/io/featurehub/dacha/resource/DachaApiKeyResource.kt
- backend/sse-edge-stats-api/async-api.yaml
- backend/sse-edge/src/main/java/io/featurehub/edge/StreamingFeatureSource.java
- backend/sse-edge/src/main/java/io/featurehub/edge/client/ClientConnection.java
- backend/sse-edge/src/main/java/io/featurehub/edge/client/TimedBucketClientConnection.java
- backend/sse-edge/src/main/java/io/featurehub/edge/rest/EventStreamResource.java
- backend/sse-edge/src/main/java/io/featurehub/edge/strategies/ClientContext.java
- backend/sse-edge/src/main/kotlin/io/featurehub/edge/features/DachaFeatureRequestSubmitter.kt
- backend/sse-edge/src/main/kotlin/io/featurehub/edge/features/DachaRequestOrchestrator.kt
- backend/sse-edge/src/main/kotlin/io/featurehub/edge/features/EtagHolder.kt
- backend/sse-edge/src/main/kotlin/io/featurehub/edge/features/FeatureRequestCollection.kt
- backend/sse-edge/src/main/kotlin/io/featurehub/edge/features/FeatureRequestCompleteNotifier.kt
- backend/sse-edge/src/main/kotlin/io/featurehub/edge/features/FeatureRequestResponse.kt
- backend/sse-edge/src/main/kotlin/io/featurehub/edge/features/FeatureRequester.kt
- backend/sse-edge/src/main/kotlin/io/featurehub/edge/features/FeatureRequesterSource.kt
- backend/sse-edge/src/test/groovy/io/featurehub/edge/features/EtagSplitterSpec.groovy
- backend/sse-edge/src/test/groovy/io/featurehub/edge/features/FeatureRequestCollectionSpec.groovy
- backend/sse-edge/src/test/groovy/io/featurehub/edge/features/FeatureRequestResponseSpec.groovy
- backend/sse-edge/src/test/groovy/io/featurehub/edge/features/FeatureRequestSuccessSpec.groovy
- backend/sse-edge/src/test/groovy/io/featurehub/edge/features/FeatureRequesterSpec.groovy
Implements support for etag headers for SDK clients. Etags will always be sent back but if not provided edge will operate as normal. This is part one of the ticket, the SDKs now need to be updated to support it.
Fixes #442
> Etag headers

- backend/dacha/src/main/java/io/featurehub/dacha/EnvironmentFeatures.java
- backend/dacha/src/main/java/io/featurehub/dacha/InMemoryCache.java
- backend/sse-edge/src/main/java/io/featurehub/edge/client/TimedBucketClientConnection.java
- backend/sse-edge/src/main/java/io/featurehub/edge/rest/EventStreamResource.java
- sdks/typescript/featurehub-javascript-client-sdk/app/polling_sdk.ts
- sdks/typescript/featurehub-javascript-node-sdk/app/index.ts
This is an update for extensive in-the-wild testing for typescript and
fixes an issue with etag generation in the Dacha server.
Fixes #533
- the browser was tested with the polling and SSE client, using a client and server evaluated key with context
- the node server was tested with polling and SSE client with only a server evaluated key (as only this makes sense) with context
Some updates were done as a result of this based on real life testing over discovered documentation.
> In-the-wild testing and etag support for typescript SDK

- backend/security-oauth/src/main/kotlin/io/featurehub/web/security/oauth/OAuth2Feature.kt
- pipeline/app-build-pipeline/cloudbuild.yaml
remove jersey client from oauth2 feature as it isn't required because it is defined by the OTEL client
> remove jersey2 client from security-oauth

- backend/common-web/src/main/java/io/featurehub/jersey/config/EndpointLoggingListener.java
Application liveness was behind a debug check, which was hidden as a bug because all deployment check scenarios have debug logging enabled.
> endpoint logging listener fix

- backend/common-web/src/main/kotlin/io/featurehub/jersey/DelegatingHandler.kt
Ensures the health check gets passed on instead of being service as HTML.
> Add the health check to the delegating handler

- sdks/typescript/featurehub-javascript-client-sdk/README.md
- sdks/typescript/featurehub-javascript-client-sdk/app/client_feature_repository.ts
- sdks/typescript/featurehub-javascript-client-sdk/package.json
- sdks/typescript/featurehub-javascript-client-sdk/test/repository_catch_release_spec.ts
- sdks/typescript/featurehub-javascript-node-sdk/package.json
When a new feature arrives, the map returns undefined not null, so the
existing code throws an error. A test was added to detect this, and then
the problem fixed.
fixes #648
> [Typescript SDK] Bug fix: Error when a new feature arrives and Catch&Release mode is active

- backend/common-web/src/main/kotlin/io/featurehub/health/MetricsHealthRegistration.kt
This change prevents the metric ports from being able to serve
html/js traffic as they will do currently (as they are picking
up the config on party-server/ish/mr).
Fixes #640
> Prevent web traffic on metric ports

- adks/e2e-sdk/.gitignore
- adks/e2e-sdk/README.adoc
- adks/e2e-sdk/app/steps/flag_steps.ts
- adks/e2e-sdk/app/steps/general_steps.ts
- adks/e2e-sdk/app/steps/nonflag_steps.ts
- adks/e2e-sdk/app/steps/setup.ts
- adks/e2e-sdk/app/support/world.ts
- adks/e2e-sdk/create-demo.sh
- adks/e2e-sdk/features/examples.feature
The example applications all require a basic setup, this change
allows the test to be run and a file will be output that will
be all ready to go.
> Create cucumber steps for featurehub-examples repository applications

- backend/common-web/src/main/kotlin/io/featurehub/rest/CorsFilter.kt
- backend/common-web/src/test/groovy/io/featurehub/rest/CorsFilterSpec.groovy
- backend/dacha/src/main/kotlin/io/featurehub/dacha/resource/DachaApiKeyResource.kt
- backend/edge-full/src/main/java/io/featurehub/edge/Application.java
- backend/edge-rest/src/main/kotlin/io/featurehub/edge/Application.kt
- backend/mr/src/main/java/io/featurehub/mr/ManagementRepositoryFeature.java
- backend/party-server-ish/src/main/kotlin/io.featurehub.party/Application.kt
- backend/party-server/src/main/kotlin/io.featurehub.party/Application.kt
The etag field was not included as an extra permissible header.
It should have been exposed as a Access-Control-Expose-Headers
for the browser SDK to be able to see it and thus allow the
browser to send back the if-none-match header.
Fixes #661
> [Bugfix] etag not in OPTIONS header, prevented browser SDK from using etag

- backend/common-web/src/main/java/io/featurehub/jersey/config/CommonConfiguration.java
- backend/common-web/src/main/kotlin/io/featurehub/rest/WebHeaderAuditLogger.kt
- backend/common-web/src/main/kotlin/io/featurehub/utils/InjectionConfig.kt
- backend/common-web/src/test/groovy/io/featurehub/rest/WebHeaderAuditLoggerSpec.groovy
- backend/composite-app/pom.xml
- backend/mr-db-api/src/main/java/io/featurehub/db/api/DBLoginSession.java
- backend/mr-db-api/src/main/kotlin/io/featurehub/db/api/SessionApi.kt
- backend/mr-db-sql/src/main/java/io/featurehub/db/services/AuthenticationSqlApi.java
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/AuthenticationSpec.groovy
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureSpec.groovy
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/RolloutStrategyValidationUtilsSpec.groovy
- backend/mr/src/main/java/io/featurehub/mr/auth/AuthApplicationEventListener.java
- backend/party-server/src/test/resources/log4j2-test.xml
- docs/installation.adoc
This change brings in three big changes to the logging
- any arbitrary environment variable can be logged in a structure (see docs)
- any web header can be captured and logged
- the user who is performing the action can be added to the logs
Fixes #660
> [Feature] Add in extra options for logging information (user, environment, web-headers)

- backend/edge-common/src/main/kotlin/io/featurehub/edge/rest/FeatureGet.kt
- docs/installation.adoc
#Description
This change allows the Infrastructure team to set the cache
control header on GET requests. If it isn't configured,
nothing is set.
Fixes #681
> Allow Infrastructure team to set cache control on Edge GET API

- backend/composite-db-drivers/pom.xml
- backend/composite-parent/pom.xml
- backend/mr-db-ebean/pom.xml
Ebean 12.15.0 has fully support for h2 v2, and postgres is a CVE.
> [Maint] Upgrade Postgres for CVE and Ebean deps

- admin-frontend/open_admin_app/lib/widgets/apps/manage_app_bloc.dart
- admin-frontend/open_admin_app/lib/widgets/features/per_application_features_bloc.dart
- admin-frontend/open_admin_app/pubspec.yaml
The latest version of Google Fonts caused breakages as it didn't limit
itself to Flutter 2.10 and beyond, this was causing the build to break.
> [internal] Force specific version of Google Fonts

- backend/edge-stats-api/async-api.yaml
This is an internal change that is designed to increase sharability of the API.
> [internal] Force the package name for Edge Statistics

- backend/edge-full/src/main/java/io/featurehub/edge/bucket/BucketService.java
- backend/edge-full/src/main/java/io/featurehub/edge/bucket/EventOutputBucketService.java
- backend/edge-full/src/main/java/io/featurehub/edge/bucket/TimedBucket.java
- backend/edge-full/src/main/java/io/featurehub/edge/bucket/TimedBucketSlot.java
- backend/edge-full/src/main/java/io/featurehub/edge/bucket/TimerBucketPurpose.java
- backend/edge-full/src/main/java/io/featurehub/edge/client/ClientConnection.java
- backend/edge-full/src/main/java/io/featurehub/edge/client/TimedBucketClientConnection.java
- backend/party-server/src/test/resources/log4j2-test.xml
Dropping connections for SSE is best used for when SSE is being cached and for dealing with ghost
connections. If there is no cache layer, it is worthwhile to be able to remove the drop connections
and simply use a heartbeat to manage connections instead. This PR adds heartbeat capability to allow
both a heartbeat and dropping connections, and _only_ a heartbeat to manage connections for SSE.
> [feature] Support Heartbeats in SSE

- backend/composite-db-drivers/pom.xml
- e2e/test/features/service_accounts_load.feature
- e2e/test/steps/AdminPortfolioStepdefs.dart
- e2e/test/steps/PortfolioStepdefs.dart
It was causing database issues for MariaDB applications so we have rolled back to
the latest of the 2.7 series (2.7.5 released 15 Jan, 2022).
This also introduces some resiliency in the e2e tests to be able to run multiple
times.
> [internal] MariaDB driver 3.0.3 is not ready for primetime

- backend/security-oauth/Dockerfile
This will allow keycloak to run as a standalone app
and also serve the image. It uses the root user
so that the image can write to its own disk.
> [internal] Add a Dockerfile for keycloak

- backend/common-web/src/main/java/io/featurehub/jersey/config/EndpointLoggingListener.java
- backend/common-web/src/main/kotlin/io/featurehub/health/MetricsHealthRegistration.kt
- backend/common-web/src/main/kotlin/io/featurehub/jersey/ApplicationLifecycleListener.kt
issues exist around the application lifecycle listener being
attached to multiple contexts and triggering before the whole
app is fully registered. This separates the two.
> [internal] ensure lifecycle listener is registered only once

- backend/edge-full/src/main/java/io/featurehub/edge/NamedCacheFeatureStreamListener.java
- backend/edge-full/src/main/java/io/featurehub/edge/StreamingFeatureSource.java
- backend/edge-full/src/main/java/io/featurehub/edge/rest/SSEHeaderFilter.java
- backend/edge-full/src/main/kotlin/io/featurehub/edge/stats/Stat.kt
- backend/edge-full/src/main/kotlin/io/featurehub/edge/stats/StatDisruptor.kt
- backend/edge-full/src/main/kotlin/io/featurehub/edge/stats/StatEventHandler.kt
- backend/edge-full/src/main/kotlin/io/featurehub/edge/stats/StatKeyEventCollection.kt
- backend/edge-full/src/main/kotlin/io/featurehub/edge/stats/StatTimeTrigger.kt
- backend/edge-full/src/main/kotlin/io/featurehub/edge/stats/StatsCollectionOrchestrator.kt
- backend/edge-full/src/main/kotlin/io/featurehub/edge/stats/StatsFeature.kt
In SSEHeaderFilter, removed unwanted IOException
In Stat.kt and StatsCollectionOrchestrator.kt - Specified type explicitly to avoid unchecked nullability issues from a declaration where the type was inferred from a platform call.
In StatEventHandler, replaced .map(){}.toMap() with associateWith()
In StatTimeTrigger, made timer private to avoid indecent exposure code smell. Also, public access specifier was redundant for shutdownTimer()
> Minor refactoring

- backend/common-web/src/main/kotlin/io/featurehub/jersey/DelegatingHandler.kt
Due to a filtering issue, the icon was not being served properly - it was HTML.
> [internal/icon-fix] icon not being served properly

- admin-frontend/src/main/resources/post-build-assembly.xml
- admin-frontend/src/main/resources/pre-build-assembly.xml
- backend/security-oauth/src/main/kotlin/io/featurehub/web/security/oauth/OAuth2JerseyClient.kt
- backend/security-oauth/src/main/kotlin/io/featurehub/web/security/oauth/providers/GenericOAuthProvider.kt
- backend/security-oauth/src/main/kotlin/io/featurehub/web/security/oauth/providers/OAuth2Provider.kt
- backend/security-oauth/src/test/groovy/io/featurehub/web/security/oauth/providers/GroovyOAuthProviderSpec.groovy
- backend/security-oauth/src/test/groovy/io/featurehub/web/security/oauth/providers/OAuth2JerseyClientSpec.groovy
- docs/modules/ROOT/pages/identity.adoc
Support extra headers and form entries for oauth2
generic provider. fixes #775
> [feature/oauth2-generic-headers] oauth2 token headers and form

- backend/security-oauth/src/main/kotlin/io/featurehub/web/security/oauth/providers/GenericOAuthProvider.kt
generic oauth was using accessToken from openid instead of the
proper idToken. This swaps it by default to idToken but allows the
old behaviour.
> [internal/bugfix] - generic oauth needs to use idToken

- backend/mr-db-ebean/src/main/resources/dbmigration/h2/1.15.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mysql/1.15.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/oracle/1.15.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/postgres/1.15.sql
The database migration should have set the field to upper case by default.
> [internal/fix-migration] Database migration for person vs admin service account

- backend/common-db/src/main/kotlin/io/featurehub/app/db/utils/DatabaseHealthSource.kt
- backend/composite-logging/pom.xml
Tag the DatabaseHealthCheck so it can be filtered using the `connect.disable-logs` MDC entry. None of the standard log4j2 filter would solve this issue.
> [internal/noisy-database] Support the disabling noisy database logs

- adks/e2e-sdk/app/steps/flag_steps.ts
- adks/e2e-sdk/app/steps/setup.ts
- backend/common-db/src/main/kotlin/io/featurehub/app/db/utils/CommonDbFeature.kt
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.0__initial.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.1.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.10.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.11.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.12.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.13.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.14.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.15.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.2.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.4.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.5.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.6.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.7__dropsFor_1.3.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.8.sql
- backend/mr-db-ebean/src/main/resources/dbmigration/mariadb/1.9.sql
- backend/mr-db-ebean/src/test/java/io/featurehub/db/GenerateDbMigration.java
- backend/mr/src/main/resources/deploy-defaults/log4j2.xml
- backend/party-server/src/main/resources/deploy-defaults/log4j2.xml
Existing MariaDB users should see no change in migrations, they were copied from
MySQL migrations, but moving forward we will support MySQL 8+ and MariaDB 10.5+
as separate databases with separate database drivers and separate sample installs.
> [feature/support-maria-db] Formally support MariaDB

- admin-frontend/open_admin_app/lib/api/client_api.dart
- e2e/lib/superuser_common.dart
- e2e/lib/util.dart
- e2e/test/steps/ApplicationStepdefs.dart
- e2e/test/steps/EnvironmentStepdefs.dart
- e2e/test/steps/UserStateStepdefs.dart
Upgrade to OpenAPI 6 for Dart introduced minor compatibility issues, these are addressed in this PR.
> [internal/dart-open-api-upgrade] OpenAPI 6.0.1 / 6.1 Dart upgrade

- backend/mr-db-sql/src/main/java/io/featurehub/db/publish/NATSPublisher.java
The feature update listener was  not being setup "technically" correctly. In essence it didn't matter for the code base, it affects testability and extensibility.
> [internal/nats-publisher-config] Minor issue with NATS Publisher config

- backend/mr/pom.xml
- backend/mr/src/main/java/io/featurehub/Application.java
- backend/party-server-ish/pom.xml
- backend/party-server-ish/src/main/kotlin/io.featurehub.party/Application.kt
- backend/release.sh
- backend/security-oauth/src/main/kotlin/io/featurehub/web/security/oauth/OAuth2Feature.kt
- backend/security-saml/src/main/kotlin/io/featurehub/web/security/saml/EnvironmentalSamlServiceProviderConfig.kt
SAML logins were not allowed to exist on their own without OAuth2 also.
This fixes the issue where a SAML login being the only available login, or SAML being available as login separately from local login would not display without OAuth2 also being configured.
> [bugfix/SAML] Single login bugfix

- docs/modules/ROOT/pages/users.adoc
If there is only a single Super Admin user in the system, you must use the database to reset their password. Fixes #158
> [internal/lost-superuser-password] How to reset password when a single Super Admin

- backend/common-web/src/main/kotlin/io/featurehub/health/MetricsHealthRegistration.kt
- backend/common-web/src/main/kotlin/io/featurehub/jersey/AdminAppStaticHttpHandler.kt
- backend/common-web/src/main/kotlin/io/featurehub/jersey/DelegatingHandler.kt
- backend/common-web/src/main/kotlin/io/featurehub/jersey/FeatureHubJerseyHost.kt
- backend/mr-db-api/src/main/java/io/featurehub/db/api/OrganizationApi.java
- backend/mr-db-sql/src/main/java/io/featurehub/db/services/OrganizationSqlApi.java
- backend/mr/src/main/java/io/featurehub/mr/resources/SetupResource.java
- backend/mr/src/main/resources/deploy-defaults/common.properties
- backend/party-server/src/test/resources/application.properties
Regardless of the featurehub.url-path provided to change the context for the application, the metric and health check urls should response on / as, particularly metrics, they are the traditional locations. We also need to leave them where they are so existing deployments don't fail on upgrade.
Fixes #853
> [bufgix/internal-urls] Mount metrics and health on /

- admin-frontend/build/build.sh
- backend/party-server/src/test/resources/application.properties
The canvaskit url for the intranet site needs to be relative.
Fixes #855
> [bufgix/intranet-canvaskit] Ensure canvaskit loads using a relative url

- admin-frontend/open_admin_app/lib/api/client_api.dart
- admin-frontend/open_admin_app/lib/common/person_state.dart
- admin-frontend/open_admin_app/lib/routes/features_overview_route.dart
- admin-frontend/open_admin_app/lib/widgets/apps/group_permissions_widget.dart
- admin-frontend/open_admin_app/lib/widgets/features/create_update_feature_dialog_widget.dart
- admin-frontend/open_admin_app/lib/widgets/features/feature_names_left_panel.dart
- admin-frontend/open_admin_app/lib/widgets/features/set_feature_metadata.dart
- admin-frontend/open_admin_app/lib/widgets/service-accounts/service_accounts_env_bloc.dart
- backend/mr-api/mr-api.yaml
- backend/mr-db-api/src/main/java/io/featurehub/db/api/ApplicationApi.java
- backend/mr-db-api/src/main/java/io/featurehub/db/api/PersonFeaturePermission.java
- backend/mr-db-api/src/main/kotlin/io/featurehub/db/api/EnvironmentApi.kt
- backend/mr-db-services/src/main/kotlin/io/featurehub/db/services/Conversions.kt
- backend/mr-db-services/src/main/kotlin/io/featurehub/db/services/ConvertUtils.kt
- backend/mr-db-sql/src/main/java/io/featurehub/db/services/ApplicationSqlApi.java
- backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/EnvironmentSqlApi.kt
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/ApplicationSpec.groovy
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/AuthenticationSpec.groovy
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/BaseSpec.groovy
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Environment2Spec.groovy
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/GroupSpec.groovy
- backend/mr/src/main/java/io/featurehub/mr/resources/FeatureResource.java
- backend/mr/src/main/java/io/featurehub/mr/resources/RolloutStrategyResource.java
- backend/mr/src/main/java/io/featurehub/mr/utils/ApplicationUtils.java
- backend/mr/src/test/groovy/io/featurehub/mr/utils/ApplicationUtilsSpec.groovy
- e2e/test/steps/ApplicationStepdefs.dart
Create new application feature level permission, to just "create" features, thus adding ability for a group to only create features, without allowing them to delete or edit. We are keeping the original permission to "Create, edit and delete"- which allows all operations on the feature, also for backwards-compatibility of existing groups. 
Fixes #802
> [feature/feature-edit-vs-create] Feature permissions edit vs create

- backend/composite-common/pom.xml
- backend/composite-db-drivers/pom.xml
- backend/composite-parent/pom.xml
The major upgrade to jaxb causes issues with ebean migrations. Will wait for ebean 14 before upgrade.
> [internal/reverse-jaxb] Security updates for dependencies

- admin-frontend/open_admin_app/lib/api/client_api.dart
- admin-frontend/open_admin_app/lib/widgets/apps/apps_bloc.dart
This change allows for landing widgets to turn
up when the Applications page shows.
> Allow for landing overlays on App page

- admin-frontend/open_admin_app/lib/api/client_api.dart
- admin-frontend/open_admin_app/lib/common/fh_shared_prefs.dart
- admin-frontend/open_admin_app/lib/common/person_state.dart
- admin-frontend/open_admin_app/lib/common/stream_valley.dart
- admin-frontend/open_admin_app/lib/widgets/user/signin/signin_widget.dart
The shared state for which currently selected portfolio and application were a bit messy and spread around. This had led to some confusion when the app refreshes about which portfolio and application it should be using. This tidies that code up, centralises it, sorts out how it is initialized and used and makes it work in a predictable way.
Fixes #954
> [bugfix/dashboard-refresh] Fix refresh of dashboard

- docs/modules/ROOT/pages/configuration.adoc
NATS as used by FeatureHub has various channels (some optional, some dependent on which cache layer). This adds the documentation required to understand what those channels are particularly if you are securing your NATs installs.
Fixes #947
> Details of NATS channels used by FeatureHub

- admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/individual_strategy_bloc.dart
- admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/custom_strategy_bloc.dart
Strategy ids must be 4 digits (not uuids) and they cannot be changed once set as the backend relies on them.
Fixes #970
> [internal/strategy-id] Front end cannot change strategy ids

- admin-frontend/open_admin_app/lib/widgets/apps/group_permissions_widget.dart
- admin-frontend/open_admin_app/lib/widgets/apps/manage_app_bloc.dart
When you update a feature permission for a group, and then try  and update again, you get the wrong permissions. This corrects the issue.
Fixes #965
> [internal/feature-perm-fixup] Feature perms not remembering past 1st

- docs/modules/ROOT/pages/installation.adoc
The setup instructions present on [this page](https://docs.featurehub.io/featurehub/latest/installation.html#_option_2a_streaming_scalable_deployment) for Kubernetes helm has a broken link. 
Current Link: https://github.com/featurehub-io/featurehub-install/tree/master/helm
Updated Link: https://github.com/featurehub-io/featurehub-helm
I've fixed the correct link in this PR.
- [] This change requires a documentation update
> Fixed Helm Repo Link in Documentation

- admin-frontend/open_admin_app/lib/api/identity_providers.dart
- admin-frontend/open_admin_app/lib/routes/apps_route.dart
- admin-frontend/open_admin_app/lib/routes/manage_portfolios_route.dart
- admin-frontend/open_admin_app/lib/widgets/apps/apps_bloc.dart
- admin-frontend/open_admin_app/lib/widgets/portfolio/portfolio_bloc.dart
- backend/composite-ebean/pom.xml
- backend/mr-api/mr-api.yaml
- backend/mr-db-api/src/main/kotlin/io/featurehub/db/api/CacheRefresherApi.kt
- backend/mr-eventing-common/src/main/kotlin/io/featurehub/mr/events/common/CacheBroadcast.kt
- backend/mr-eventing-common/src/main/kotlin/io/featurehub/mr/events/common/CacheSource.kt
- backend/mr-eventing-common/src/main/kotlin/io/featurehub/mr/events/common/CloudEventCacheBroadcaster.kt
- backend/mr-eventing-nats/src/main/kotlin/io/featurehub/db/publish/nats/NatsDachaBroadcaster.kt
- backend/mr-eventing-nats/src/main/kotlin/io/featurehub/db/publish/nats/NatsDachaCacheFiller.kt
- backend/mr-eventing/src/main/kotlin/io/featurehub/db/publish/DbCacheSource.kt
- backend/mr-eventing/src/main/kotlin/io/featurehub/db/publish/DummyPublisher.kt
- backend/mr-eventing/src/main/kotlin/io/featurehub/mr/events/EventingFeature.kt
- backend/mr/src/main/java/io/featurehub/mr/resources/SetupResource.java
- backend/mr/src/main/kotlin/io/featurehub/mr/ManagementRepositoryFeature.kt
- backend/mr/src/main/kotlin/io/featurehub/mr/resources/CacheResource.kt
- backend/mr/src/main/kotlin/io/featurehub/mr/utils/ConfigurationUtils.kt
- backend/mr/src/main/resources/deploy-defaults/common.properties
- backend/party-server-ish/src/main/kotlin/io.featurehub.party/Application.kt
- backend/party-server/src/main/kotlin/io.featurehub.party/Application.kt
- infra/api-bucket/files/mrapi/1.1.11.yaml
In the case where for some reason there might be the suspicion of cache poisoning, this change allows republishing the cache of the entire system, individual portfolios or individual applications from the UI.
> [feature/dacha1-ui-refresh] Allow refresh of Dacha1 cache from UI

- backend/dacha2/src/main/kotlin/io/featurehub/dacha2/Dacha2CacheImpl.kt
- backend/dacha2/src/test/groovy/io/featurehub/dacha2/Dacha2CacheImplSpec.groovy
- backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/MessagingFeature.kt
API keys in Dacha2 (and hence Party Server) are not  being removed if they changed.
Fixes #998
> [bugfix/dacha2-reset-api-key] Cache not expiring changing api keys

- backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/EnvironmentSqlApi.kt
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Environment2Spec.groovy
- backend/webhook-feature-update/sinatra-example/webhook_app.rb
Portfolio Admins were left off the permission group to automatically gain access to all environments under an application. This fixes this issue.
> [internal/feature-history] Allow portfolio group admin full access to feature history

- backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/PersonSqlApi.kt
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/AdminServiceAccount2Spec.groovy
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/AdminServiceAccount3Spec.groovy
- backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Base3Spec.groovy
When a service account is updated, group updates are ignored. The code was supposed to prevent email address udpates, but it also prevented unarchiving admin service accounts and updating their groups.
Fixes #1031
> [bugfix/service-accounts] Admin Service Account groups don't update

- admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/edit_feature_value_widget.dart
- backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt
Fixes issue where a person can have be in two or more groups, where the last one assigned gives read only access which prevents them from updating feature values.
Fixes #1075
> [bugfix/account-perm] Fix multi-group permission issue

- backend/common-web/pom.xml
- backend/common-web/src/main/kotlin/io/featurehub/lifecycle/TelemetryFeature.kt
- backend/eventing-cloudevents/src/main/kotlin/io/featurehub/events/CloudEventsTelemetryReaderImpl.kt
- docs/modules/ROOT/pages/configuration.adoc
- e2e/Dockerfile
Supports full client customisation, OLTP exporters, extra header types and Zipkin (defaults to standard W3C headers) support as per https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure
> [feature] OpenTelemetry Upgrade

- admin-frontend/open_admin_app/lib/theme/custom_text_style.dart
- admin-frontend/open_admin_app/lib/widgets/apps/service_account_permissions_widget.dart
- admin-frontend/open_admin_app/lib/widgets/common/decorations/fh_page_divider.dart
- admin-frontend/open_admin_app/lib/widgets/common/fh_info_card.dart
- admin-frontend/open_admin_app/lib/widgets/environments/env_list_widget.dart
- admin-frontend/open_admin_app/lib/widgets/features/cell-view/value_cell.dart
- admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/edit_feature_value_widget.dart
- admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/feature_value_updated_by.dart
- admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/lock_unlock_switch.dart
- admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/split_add.dart
- admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/strategy_card_widget.dart
- admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/valueeditors/edit_json_value_container.dart
- admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/valueeditors/edit_number_value_container.dart
- admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/valueeditors/edit_string_value_container.dart
- admin-frontend/open_admin_app/lib/widgets/strategyeditor/editing_rollout_strategy.dart
- docs/modules/ROOT/pages/features.adoc
Improvements around layout and UI in the feature editing side sheet. Also includes a fix for #1094
Fixes #1094
Fixes an issue where cancelling edits on the strategy would not reset the values back to the original
UI tests
> Feature value editing UI improvements, plus fix for unexpected locking error
