featurehub-io/featurehub

sdks/typescript/client-typescript-core/package-lock.json, sdks/typescript/client-typescript-core/package.json, sdks/typescript/client-typescript-eventsource/package.json
Reflects the documentation changes from @IrinaSouth pushed to repository.
=> releases for typescript

sdks/typescript/client-typescript-core/package.json, sdks/typescript/client-typescript-eventsource/package.json
=> npm keywords update

admin-frontend/app_singleapp/lib/widgets/features/feature_dashboard_constants.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_names_left_panel.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_value_row_boolean.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_value_row_json.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_value_row_locked.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_value_row_number.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_value_row_string.dart, admin-frontend/app_singleapp/lib/widgets/user/list/list_users_widget.dart, admin-frontend/app_singleapp/pubspec.yaml, pom.xml
Resolves https://github.com/featurehub-io/featurehub/issues/135
Also contains minor styling fixes for the user info page
=> Feature/lock unlock feature 

sdks/typescript/client-typescript-eventsource/package-lock.json, sdks/typescript/client-typescript-eventsource/package.json
=> released for updated docs for npm lib

sdks/typescript/client-typescript-core/package.json, sdks/typescript/client-typescript-eventsource/package.json
=> npm release steps

backend/sse-edge/src/main/java/io/featurehub/edge/FeatureTransformerUtils.java
=> Expose locked status from Edge

admin-frontend/app_singleapp/lib/widgets/features/feature_names_left_panel.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_value_row_boolean.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_value_row_json.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_value_row_locked.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_value_row_number.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_value_row_string.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_value_updated_by.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_values_bloc.dart
As per ticket.
Fixes # 153
See test plan
=> Resolves issue around issue saving no longer working.

admin-frontend/app_singleapp/lib/widgets/features/feature_value_row_json.dart, admin-frontend/build-frontend.sh, admin-frontend/build/build.sh, backend/build-docker.sh, docs/index.adoc, pipeline/build/flutter_web/Dockerfile, pipeline/build/flutter_web/make-image.sh
Minor changes and script updates for 0.0.7 release
=> release of 0.0.7

docs/index.adoc, docs/installation.adoc
Fix installation instructions
- [x ] This change requires a documentation update
=> amend installation docs

backend/sse-edge/src/main/java/io/featurehub/edge/FeatureTransformerUtils.java, backend/sse-edge/src/main/java/io/featurehub/edge/ServerConfig.java, sdks/java/client-java-android/src/main/java/io/featurehub/android/FeatureHubClient.java, sdks/java/client-java-android/src/test/groovy/io/featurehub/android/FeatureHubClientSpec.groovy, sdks/java/client-java-android/src/test/java/io/featurehub/android/FeatureHubClientRunner.java, sdks/java/client-java-core/README.adoc, sdks/java/client-java-core/src/main/java/io/featurehub/client/ClientContext.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/ClientContextRepository.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/ClientFeatureRepository.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/FeatureRepository.java, sdks/java/client-java-core/src/test/groovy/io/featurehub/client/RepositorySpec.groovy, sdks/java/client-java-jersey/pom.xml, sdks/java/client-java-jersey/src/main/java/io/featurehub/client/jersey/JerseyClient.java, sdks/java/client-java-jersey/src/test/groovy/io/featurehub/client/jersey/JerseyClientSpec.groovy, sdks/java/client-java-jersey/src/test/java/io/featurehub/client/jersey/JerseyClientSample.java
=> Java SDK client for server side strategy rollouts.

backend/mr-api/strategy-enums.yaml, sdks/client-csharp/FeatureHubSDK/src/IO.FeatureHub.SSE/Model/StrategyAttributeDeviceName.cs, sdks/dart/client-dart-api/lib/model/strategy_attribute_device_name.dart, sdks/typescript/client-typescript-core/app/client_feature_repository.ts
=> increase possible devices

admin-frontend/app_singleapp/lib/widgets/features/hidden_environment_list.dart, admin-frontend/app_singleapp/lib/widgets/features/table-collapsed-view/value_not_set_container.dart
selected needed a colour, changed the way
that we react to changes.
Fixes #202 
Manual.
=> resolve issue with chips

admin-frontend/app_singleapp/lib/widgets/features/environments_features_list_view.dart, admin-frontend/app_singleapp/lib/widgets/features/table-collapsed-view/value_cell.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/split_rollout_button.dart
Fix null values on collapsed feature value display for strategies
Fixes # 68
=> handle null value as not set

admin-frontend/app_singleapp/lib/widgets/common/fh_tag.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_value_cell.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/boolean/boolean_cell_holder.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/create-strategy-widget.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/edit_value_strategy_link_button.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/json/json_cell_holder.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/number/number_cell_holder.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/split_rollout_button.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/string/string_cell_holder.dart
=> fix permissions issues related to feature value editing

admin-frontend/app_singleapp/lib/widgets/features/table-collapsed-view/value_cell.dart
=> fix "not set" value display in collapsed view

admin-frontend/app_mr_layer/pom.xml, admin-frontend/app_mr_layer/pubspec.yaml, admin-frontend/app_singleapp/lib/widgets/features/per_feature_state_tracking_bloc.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/number/edit_number_value_container.dart, admin-frontend/app_singleapp/lib/widgets/features/tabs_bloc.dart
=> resolves sizing when adding new strategy

admin-frontend/app_singleapp/lib/widgets/features/custom_strategy_bloc.dart, admin-frontend/app_singleapp/lib/widgets/features/per_application_features_bloc.dart, admin-frontend/app_singleapp/lib/widgets/features/per_feature_state_tracking_bloc.dart, admin-frontend/app_singleapp/lib/widgets/features/percentage_utils.dart, admin-frontend/app_singleapp/lib/widgets/features/table-collapsed-view/value_cell.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/create-strategy-widget.dart, admin-frontend/app_singleapp/lib/widgets/features/tabs_bloc.dart
=> surfacing validations in admin UI

admin-frontend/app_singleapp/lib/widgets/features/environments_features_list_view.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_value_cell.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/create-strategy-widget.dart, admin-frontend/app_singleapp/lib/widgets/features/tabs_bloc.dart
As per ticket description
Fixes #219 
UI testing once the bug was understood.
=> complex cell layout issue across strategies.

admin-frontend/app_singleapp/lib/widgets/features/feature_dashboard_constants.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_value_cell.dart, admin-frontend/app_singleapp/lib/widgets/features/per_feature_state_tracking_bloc.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/boolean/boolean_cell_holder.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/boolean/boolean_strategy_card.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/boolean/edit_boolean_value_dropdown_widget.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/json/json_cell_holder.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/lock_unlock_switch.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/number/number_cell_holder.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/string/string_cell_holder.dart
issue with cell not redrawing properly, both strategies
and default value were not tracking.
Hand tested
=> issue with cell not redrawing properly, both strategies

docs/index.adoc
=> how rollout strategies work over all

backend/sse-edge/src/main/java/io/featurehub/edge/strategies/ApplyFeature.java, backend/sse-edge/src/main/java/io/featurehub/edge/strategies/ClientAttributeCollection.java, sdks/client-csharp/FeatureHubSDK/FeatureHub.cs, sdks/client-csharp/FeatureHubTestProject/FeatureHubRepositoryTest.cs, sdks/dart/client-dart-sdk/lib/src/repository.dart, sdks/dart/client-dart-sdk/test/src/repository_test.dart, sdks/java/client-java-core/src/main/java/io/featurehub/client/ClientFeatureRepository.java, sdks/java/client-java-core/src/test/groovy/io/featurehub/client/RepositorySpec.groovy, sdks/typescript/client-typescript-core/app/client_feature_repository.ts, sdks/typescript/client-typescript-eventsource/app/featurehub_eventsource.ts
With server side evaluation of strategies, we can get the same version with a different value.
=> Ensure same version but different value triggers update

admin-frontend/app_singleapp/lib/routes/register_url_route.dart, admin-frontend/app_singleapp/lib/widgets/common/fh_json_editor.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/lock_unlock_switch.dart
Add tiptools for lock/unlock function when editing features
Fix dart analysis issues
=> locked/unlocked tiptool + dart analysis fixes

sdks/typescript/client-typescript-eventsource/README.md
Documentation update for the typescript SDK
=> update typescript doc

docs/index.adoc, docs/installation.adoc
DO NOT MERGE UNTIL MILESTONE 1.0
This PR collects all the changes required for the 1.0 release related to documentation.
=> Milestone 1.0 changes

docs/index.adoc
minor docs update for strategies section
=> docs update

admin-frontend/app_singleapp/lib/widgets/user/common/portfolio_group.dart, backend/composite-app/pom.xml, backend/composite-ebean/pom.xml, backend/composite-opentracing/pom.xml, backend/composite-prometheus/pom.xml, backend/dacha-api/pom.xml, backend/dacha/pom.xml, backend/mr-api/pom.xml, backend/mr-db-api/pom.xml, backend/mr-db-sql/pom.xml, backend/mr-publish-api/pom.xml, backend/mr-streaming-api/pom.xml, backend/mr/pom.xml, backend/mr/src/main/java/io/featurehub/mr/auth/AuthApplicationEventListener.java, backend/party-server/pom.xml, backend/sse-edge/pom.xml, backend/sse-strategy-matchers/pom.xml, sdks/dart/client-dart-api/pom.xml, sdks/dart/client-dart-api/pubspec.yaml, sdks/dart/client-dart-sdk/pom.xml
Allow build to build on a machine with no history of the app.
Maven Repository removed.
=> The build was not working if you didn't have eons of existing

docs/capabilities-table.adoc
Update to the capabilities of the SDKs.
=> feature capability table update

backend/mr-api/user.yaml, backend/mr-db-api/src/main/java/io/featurehub/db/api/UserStateApi.java, backend/mr-db-sql/src/main/java/io/featurehub/db/services/UserStateSqlApi.java, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/UserStateSpec.groovy, backend/mr/src/main/java/io/featurehub/mr/resources/UserStateResource.java
This ensures that the data being stored in the user
state is valid.
Fixes #104
=> Fix user state possible leak

.gitignore, admin-frontend/app_singleapp/assembly.xml, admin-frontend/app_singleapp/pom.xml, admin-frontend/pipeline-build.sh, pipeline/app-build-pipeline/cloudbuild.yaml, pipeline/app-master-pipeline/cloudbuild.yaml, pom-front-end.xml, pom.xml
This is the build for both the frontend and backend and supports differential builds. It will only build the frontend if one of the elements in the tree has changed, and will only build from the backend that which has changed.
=> remove the install as it was double attaching sources

admin-frontend/app_singleapp/lib/widgets/common/fh_scaffold.dart, admin-frontend/app_singleapp/lib/widgets/features/environments_features_list_view.dart, admin-frontend/app_singleapp/lib/widgets/features/feature_names_left_panel.dart, admin-frontend/app_singleapp/lib/widgets/features/features_overview_table_widget.dart, admin-frontend/app_singleapp/lib/widgets/features/table-collapsed-view/value_cell.dart
fixes overflow issues on mobile and minor responsive fixes for the features table
=> fix bottom overflow on mobile and features table display

admin-frontend/app_singleapp/lib/api/client_api.dart, admin-frontend/app_singleapp/lib/api/web_interface/io_url_handler.dart, admin-frontend/app_singleapp/lib/api/web_interface/url_handler.dart, admin-frontend/app_singleapp/lib/api/web_interface/url_handler_stub.dart, admin-frontend/app_singleapp/lib/api/web_interface/web_url_handler.dart
This removes web specific stuff from the MR block into a separate bloc of code ready for mobilisation of the code base.
Tested against Mobile and Web Versions.
=> devolve web stuff out

docs/index.adoc
=> some updates on the docs as I see them

docs/index.adoc
Documentation update - strategies
=> main docs updates

docs/index.adoc, sdks/typescript/client-typescript-eventsource/README.md
=> update readme for typescript sdk

sdks/client-csharp/FeatureHubSDK/README.md
Update C# SDK docs according to the version 1.2.0 FH release
=> c sharp sdk docs update

docs/index.adoc, docs/installation.adoc
update docs to reference latest version
=> update to v 1.1.1

admin-frontend/app_mr_layer/pom.xml, admin-frontend/app_mr_layer/pubspec.yaml, admin-frontend/app_singleapp/lib/routes/service_env_route.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/strategies/add_attribute_strategy_widget.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/strategies/rollout_strategies_widget.dart, backend/dacha-api/pom.xml, backend/mr-api/mr-api.yaml, backend/mr-api/pom.xml, backend/mr-streaming-api/pom.xml, backend/sse-edge-api/pom.xml, e2e/pubspec.yaml, e2e/test/steps/AdminGroupStepdefs.dart, e2e/test/steps/ApplicationStepdefs.dart, e2e/test/steps/EnvironmentStepdefs.dart, e2e/test/steps/PortfolioStepdefs.dart, pipeline/app-build-pipeline/cloudbuild.yaml, pipeline/app-master-pipeline/cloudbuild.yaml, sdks/dart/client-dart-api/pom.xml
Upgrade the openapi generator for Java and Dart to use the 5.0 version.
=> Openapi 5 upgrade

backend/mr/pom.xml, backend/party-server/pom.xml, pipeline/build/base_mr/default_site, pipeline/build/base_mr/make-image.sh, pipeline/build/base_party/default_site, pipeline/build/base_party/make-image.sh
Updated base docker images, updated nginx config to expose oauth2 api.
=> update the base docker image and the image used

admin-frontend/app_singleapp/lib/widgets/features/custom_strategy_bloc.dart
=> crashes on first strategy for first feature

sdks/README.adoc, sdks/typescript/client-typescript-eventsource/README.md
Documentation update for Typescript SDK
=> update docs in regards to FH initialisation

backend/composite-ebean/pom.xml, backend/mr-db-ebean/pom.xml, backend/mr-db-ebean/src/main/resources/ebean.properties, backend/mr-db-sql/docker-databases/postgres/initdb/initdb.sql, backend/mr-db-sql/pom.xml, backend/mr-db-sql/src/main/java/io/featurehub/db/utils/EbeanHolder.java, backend/mr/pom.xml, backend/mr/src/test/resources/application.properties, backend/party-server/src/test/resources/application.properties, pipeline/build/base_mr/mr.properties, pipeline/build/base_party/party.properties
MySQL driver was not included and there was an issue with the ebean code when talking to MySQL. Also MariaDB wasn't detected as a driver.
=> upgrade to new version of ebean to resolve mysql issues

admin-frontend/cli-build.sh, admin-frontend/cli/.gitignore, admin-frontend/cli/Dockerfile, admin-frontend/cli/README.adoc, admin-frontend/cli/lib/features_wu.dart, admin-frontend/cli/lib/host.dart, admin-frontend/cli/lib/identity.dart, admin-frontend/cli/lib/main.dart, admin-frontend/cli/pubspec.yaml, admin-frontend/cli/test/feature_wu.dart, admin-frontend/cli/test/sample-features.json
New functionality  - start of a command line tool. Needs to cache the bearer token and other things, but quick tool and it will be bundled in a docker image with a Dart runtime.
=> sample feature loader

admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/strategies/add_attribute_strategy_widget.dart
Correct the date helper text to ISO format.
Fixes issue #326
=> Fix date helper text

backend/composite-test/pom.xml, backend/push.sh, backend/sse-edge-api/pom.xml, backend/sse-strategy-matchers/pom.xml, sdks/java/client-java-android/pom.xml, sdks/java/client-java-core/pom.xml, sdks/java/client-java-jersey/pom.xml, sdks/java/client-java-jersey/src/main/java/io/featurehub/client/jersey/FeatureServiceImpl.java
=> Java release

sdks/client-csharp/Dockerfile, sdks/client-csharp/FeatureHubSDK/EventServiceListener.cs, sdks/client-csharp/FeatureHubSDK/FeatureHub.cs
Ambiguity fixed and comes with a Dockerfile that allows you to not have csharp installed but do a nuget release.
=> Ready for release 

sdks/client-csharp/FeatureHubSDK/FeatureHub.cs, sdks/client-csharp/FeatureHubTestProject/GoogleAnalyticsTest.cs, sdks/java/client-java-core/src/main/java/io/featurehub/client/FeatureState.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/FeatureStateBase.java, sdks/typescript/featurehub-repository/app/feature_state_holders.ts, sdks/typescript/featurehub-repository/package.json
move the interceptors behind the lock for java
the baggage example isn't behaving as expected
=> move only interceptors to behind the lock for javascript

sdks/client-csharp/Dockerfile, sdks/client-csharp/FeatureHubSDK/ClientContext.cs, sdks/client-csharp/FeatureHubSDK/EdgeFeatureHubConfig.cs, sdks/client-csharp/FeatureHubSDK/FeatureHub.cs, sdks/client-csharp/FeatureHubSDK/README.md
=> updated API and release

sdks/java/client-java-core/src/main/java/io/featurehub/client/ServerEvalFeatureContext.java, sdks/java/client-java-core/src/test/groovy/io/featurehub/client/ServerEvalContextSpec.groovy, sdks/java/client-java-jersey/src/main/java/io/featurehub/client/jersey/FeatureServiceImpl.java
Minor issues with Java SDK.
Url used for test api for jersey was not correct
null header for server eval key was not working.
=> minor java-sdk fixes

sdks/java/client-java-core/CHANGELOG.adoc, sdks/java/client-java-core/README.adoc, sdks/java/client-java-core/src/main/java/io/featurehub/client/BaseClientContext.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/ClientFeatureRepository.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/EdgeFeatureHubConfig.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/FeatureHubConfig.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/FeatureState.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/FeatureStateBase.java, sdks/java/client-java-core/src/test/groovy/io/featurehub/client/ListenerSpec.groovy, sdks/java/client-java-core/src/test/groovy/io/featurehub/client/RepositorySpec.groovy
Minor API changes to match Typescript and C#
=> Minor friendlyness API changes for Java to match

sdks/typescript/featurehub-javascript-client-sdk/README.md, sdks/typescript/featurehub-javascript-client-sdk/package.json, sdks/typescript/featurehub-javascript-node-sdk/package.json
=> Update documentation for client and server javascript sdks

backend/composite-common/pom.xml, backend/composite-jackson/pom.xml, backend/composite-jersey/pom.xml, backend/composite-logging-api/pom.xml, backend/composite-logging/pom.xml, backend/composite-parent/pom.xml, backend/composite-test/pom.xml
Also clean up the dependency releases.
Fixes #388
=> Upgrade to new Spock release

admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/strategies/add_attribute_strategy_widget.dart
=> Fix missing attribute values

backend/composite-app/pom.xml
=> upgrade high CVE issue with SnakeYAML

sdks/dart/client-dart-api/CHANGELOG.md, sdks/dart/client-dart-api/lib/api/feature_service_api.dart, sdks/dart/client-dart-api/lib/api_client.dart, sdks/dart/client-dart-api/lib/model/feature_state.dart, sdks/dart/client-dart-api/lib/model/feature_state_update.dart, sdks/dart/client-dart-api/lib/model/feature_value_type.dart, sdks/dart/client-dart-api/lib/model/role_type.dart, sdks/dart/client-dart-api/lib/model/rollout_strategy.dart, sdks/dart/client-dart-api/lib/model/rollout_strategy_attribute.dart, sdks/dart/client-dart-api/lib/model/rollout_strategy_attribute_conditional.dart, sdks/dart/client-dart-api/lib/model/rollout_strategy_field_type.dart, sdks/dart/client-dart-api/lib/model/sse_result_state.dart, sdks/dart/client-dart-api/lib/model/strategy_attribute_country_name.dart, sdks/dart/client-dart-api/lib/model/strategy_attribute_device_name.dart, sdks/dart/client-dart-api/lib/model/strategy_attribute_platform_name.dart, sdks/dart/client-dart-api/lib/model/strategy_attribute_well_known_names.dart, sdks/dart/client-dart-api/pom.xml, sdks/dart/client-dart-api/pubspec.yaml, sdks/dart/client-dart-sdk/CHANGELOG.md, sdks/dart/client-dart-sdk/example/lib/main.dart, sdks/dart/client-dart-sdk/lib/featurehub_get.dart, sdks/dart/client-dart-sdk/pubspec.yaml, sdks/dart/dart-eventsource/CHANGELOG.md, sdks/dart/dart-eventsource/pubspec.yaml, sdks/dart/dart-eventsource/test/codec_test.dart
Releasing the Dart 1.2 API with essentially the same API but null safe. Fixes #435
=> updated API code for Dart 1.2 SDK

backend/composite-app/pom.xml, backend/composite-common/pom.xml, backend/composite-ebean/pom.xml, backend/composite-jackson/pom.xml, backend/composite-jersey/pom.xml, backend/composite-logging-api/pom.xml, backend/composite-logging/pom.xml, backend/composite-opentracing/pom.xml, backend/composite-parent/pom.xml, backend/composite-prometheus/pom.xml, backend/dacha-api/pom.xml, backend/dacha/pom.xml, backend/mr-api/pom.xml, backend/mr-db-api/pom.xml, backend/mr-db-ebean/pom.xml, backend/mr-publish-api/pom.xml, backend/mr-streaming-api/pom.xml, backend/mr/pom.xml, backend/party-server/pom.xml, backend/sse-edge-api/pom.xml, backend/sse-edge-stats-api/pom.xml, backend/sse-strategy-matchers/pom.xml, backend/tile-app-with-ui/pom.xml, backend/tile-app/pom.xml, backend/tile-java/pom.xml, backend/tile-java8/pom.xml, backend/tile-release/pom.xml
Upgrades tile plugin to latest version.
=> Upgrade tiles

admin-frontend/nginx-container/Dockerfile, admin-frontend/nginx-container/default_site, admin-frontend/nginx-container/make-image.sh, admin-frontend/nginx-container/nginx.conf, backend/build.sh, backend/mr/pom.xml, backend/party-server/pom.xml, backend/pom-packages.xml, backend/tile-app/tile.xml, docs/index.adoc, pipeline/build/base_mr/Dockerfile, pipeline/build/base_mr/log4j2.xml, pipeline/build/base_mr/make-image.sh, pipeline/build/base_mr/mr.properties, pipeline/build/base_party/Dockerfile, pipeline/build/base_party/default_site, pipeline/build/base_party/log4j2.xml, pipeline/build/base_party/make-image.sh, pipeline/build/base_party/nginx.conf, pipeline/build/base_party/party.properties
The containers always require running as root. This starts the
change to fix them so they never run as root.
Fixes #409
Waiting on merge of https://github.com/featurehub-io/featurehub/pull/437 as it depends on that code.
=> Resolve Security issue with Containers

admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/individual_strategy_bloc.dart, admin-frontend/app_singleapp/lib/widgets/features/table-expanded-view/strategies/strategy_editing_widget.dart
New rules on a strategy were failing to
be processed. This fixes #450
=> Validation failing for new rules

backend/sse-edge/src/main/java/io/featurehub/edge/InflightSSEListenerRequest.java, pom.xml, sdks/java/client-java-android/pom.xml, sdks/java/client-java-android/src/main/java/io/featurehub/android/FeatureHubClient.java, sdks/java/client-java-android/src/main/java/io/featurehub/android/SSEClient.java, sdks/java/client-java-android/src/test/java/io/featurehub/android/FeatureHubClientRunner.java, sdks/java/client-java-android/src/test/resources/log4j2.xml, sdks/java/client-java-core/src/main/java/io/featurehub/client/ClientEvalFeatureContext.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/ClientFeatureRepository.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/EdgeService.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/edge/EdgeConnectionState.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/edge/EdgeReconnector.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/edge/EdgeRetryService.java, sdks/java/client-java-core/src/main/java/io/featurehub/client/edge/EdgeRetryer.java, sdks/java/client-java-core/src/test/groovy/io/featurehub/client/RepositorySpec.groovy, sdks/java/client-java-core/src/test/groovy/io/featurehub/client/StrategySpec.groovy, sdks/java/client-java-core/src/test/groovy/io/featurehub/client/edge/EdgeRetryerSpec.groovy, sdks/java/client-java-jersey/src/main/java/io/featurehub/client/jersey/JerseyClient.java, sdks/java/client-java-sse/pom.xml, sdks/java/client-java-sse/src/main/java/io/featurehub/edge/sse/SSEClient.java, sdks/java/client-java-sse/src/main/java/io/featurehub/edge/sse/SSEClientFactory.java, sdks/java/client-java-sse/src/main/resources/META-INF/services/io.featurehub.client.FeatureHubClientFactory, sdks/java/client-java-sse/src/test/groovy/io/featurehub/edge/sse/SSEClientSpec.groovy, sdks/java/client-java-sse/src/test/java/io/featurehub/edge/sse/SSEClientRunner.java, sdks/java/client-java-sse/src/test/resources/log4j2.xml, sdks/java/pom.xml
This provides an alternative SSE client for Java, along with a revamped and consistent system for dealing with timeout, connection, backoff and failure issues.
Fixes #416
=> Alternative java sse client

sdks/typescript/featurehub-javascript-client-sdk/README.md, sdks/typescript/featurehub-javascript-client-sdk/app/polling_sdk.ts, sdks/typescript/featurehub-javascript-client-sdk/package.json, sdks/typescript/featurehub-javascript-node-sdk/package.json
There are certain circumstances where the polling web based client can overwhelm the client and the FeatureHub server. This resolves that issue.
Fixes #465
=> issue with js client polling can overwhelm server

pipeline/build/base_mr/mr.properties, pipeline/build/base_party/party.properties
Update the base images so strategy headers are included by default.
=> update cors headers in base images

admin-frontend/cli/lib/feature-base.dart, admin-frontend/cli/lib/feature-strategy.dart, admin-frontend/cli/lib/features.dart, admin-frontend/cli/lib/login.dart, admin-frontend/cli/lib/portfolios.dart
Starts work on a Dart based natively compiled CLI tool.
=> started work on CLI tool for FH

backend/mr-db-api/src/main/java/io/featurehub/db/password/PasswordSalter.java, backend/mr-db-api/src/test/groovy/io/featurehub/db/password/PasswordSalterSpec.groovy, backend/mr-db-ebean/src/main/resources/dbmigration/h2/1.7__dropsFor_1.3.sql, backend/mr-db-ebean/src/main/resources/dbmigration/h2/1.8.sql, backend/mr-db-ebean/src/main/resources/dbmigration/model/1.7__dropsFor_1.3.model.xml, backend/mr-db-ebean/src/main/resources/dbmigration/model/1.8.model.xml, backend/mr-db-ebean/src/main/resources/dbmigration/mssql/1.7__dropsFor_1.3.sql, backend/mr-db-ebean/src/main/resources/dbmigration/mssql/1.8.sql, backend/mr-db-ebean/src/main/resources/dbmigration/mysql/1.7__dropsFor_1.3.sql, backend/mr-db-ebean/src/main/resources/dbmigration/mysql/1.8.sql, backend/mr-db-ebean/src/main/resources/dbmigration/postgres/1.7__dropsFor_1.3.sql, backend/mr-db-ebean/src/main/resources/dbmigration/postgres/1.8.sql, backend/mr-db-ebean/src/test/java/io/featurehub/db/GenerateDbMigration.java, backend/mr-db-sql/src/main/java/io/featurehub/db/model/DbPerson.java, backend/mr-db-sql/src/main/java/io/featurehub/db/services/AuthenticationSqlApi.java, backend/mr-db-sql/src/main/java/io/featurehub/db/services/PersonSqlApi.java
CodeQL security review indicates that the
default algorithm we are using for passwords
is now insecure, so this allows
progressive upgrade and replacement over time.
Fixes #424
=> Update the password algorithm

admin-frontend/open_admin_app/lib/api/router.dart, admin-frontend/open_admin_app/lib/routes/fh_navigator.dart
This removes the print statements from the front end which are appearing in the console.
=> remove-prints

backend/HOW_TO_RELEASE_OS.adoc, backend/push.sh, backend/tile-app-with-ui/tile.xml, backend/tile-app/tile.xml
Documentation on how to release. Also updating so builds tag latest automatically.
=> cleanup-release

backend/mr-db-models/src/main/java/io/featurehub/db/model/DbAcl.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbApplication.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbApplicationFeature.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbBase.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbEnvironment.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbFeatureValue.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbGroup.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbOrganization.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbPerson.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbPortfolio.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbRolloutStrategy.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbServiceAccount.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbServiceAccountEnvironment.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbUserState.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbVersionedBase.java
Changes to mapped superclasses and uses the ebean Model base class to simplify model use.
Internal structural change to clean up code.
=> use mapped superclasses

backend/composite-common/pom.xml, backend/mr-db-sql/src/main/java/io/featurehub/db/utils/EbeanHolder.java, docs/installation.adoc
This allows environment variable overrides for
all system properties.
Fixes #486
Manually
=> Allow environment based configuration

backend/common-web/src/main/java/io/featurehub/jersey/config/CacheJsonMapper.java, backend/common-web/src/main/kotlin/io/featurehub/lifecycle/BaseLifecycleListener.kt, backend/dacha/src/main/java/io/featurehub/dacha/CacheManager.java, backend/dacha/src/main/java/io/featurehub/dacha/ServerConfig.java, backend/mr-db-sql/src/main/java/io/featurehub/db/listener/FeatureUpdateListener.java, backend/mr-db-sql/src/main/java/io/featurehub/db/publish/NamedCacheListener.java, backend/mr-db-sql/src/main/java/io/featurehub/db/services/Conversions.java, backend/sse-edge/src/main/java/io/featurehub/edge/FeatureTransformerUtils.java, backend/sse-edge/src/main/java/io/featurehub/edge/StreamingFeatureSource.java, backend/sse-edge/src/main/java/io/featurehub/edge/client/SSEStatusMessage.java, backend/sse-edge/src/main/java/io/featurehub/edge/client/TimedBucketClientConnection.java, backend/sse-edge/src/main/kotlin/io/featurehub/edge/permission/PermissionPublishDelivery.kt, backend/sse-edge/src/main/kotlin/io/featurehub/edge/stats/NATSStatPublisher.kt, backend/sse-edge/src/main/kotlin/io/featurehub/edge/stats/StatsFeature.kt, pipeline/app-build-pipeline/diff-build.sh, pom-front-end.xml
Allows disconnected publishing, means people
can build and use something other than NATS for stats.
Moves the topic zip reader/writer into a common location.
=> NATS Publishing of Stats

sdks/typescript/featurehub-javascript-client-sdk/app/client_context.ts, sdks/typescript/featurehub-javascript-client-sdk/app/context_impl.ts, sdks/typescript/featurehub-javascript-client-sdk/app/edge_featurehub_config.ts, sdks/typescript/featurehub-javascript-client-sdk/test/client_context_spec.ts, sdks/typescript/featurehub-repository/app/client_context.ts, sdks/typescript/featurehub-repository/app/feature_hub_config.ts, sdks/typescript/featurehub-repository/test/client_context_spec.ts
This PR removes an unneeded dependency on `FeatureHubConfig` from `BaseClientContext`.
Fixes # 497
Just removed config parameter from unittests and they all pass.
=> Removed unneeded config from BaseClientContext (in javascript SDK).

sdks/typescript/featurehub-javascript-client-sdk/app/client_context.ts, sdks/typescript/featurehub-javascript-client-sdk/app/context_impl.ts, sdks/typescript/featurehub-repository/app/client_context.ts
Removed lingering imports from PR #502
=> Removed lingering imports from PR #502

sdks/typescript/featurehub-javascript-client-sdk/app/edge_featurehub_config.ts, sdks/typescript/featurehub-javascript-client-sdk/app/feature_hub_config.ts
=> fix minor issue with config api key check

sdks/typescript/featurehub-javascript-client-sdk/README.md, sdks/typescript/featurehub-javascript-client-sdk/package.json
Bumped javascript SDK to version 1.0.8.
=> Bumped up javascript SDK version to 1.0.8

sdks/typescript/featurehub-javascript-node-sdk/package.json
Bumped up javascript SDK version to 1.0.8
=> Updated featurehub-javascript-node-sdk to version 1.0.8

backend/dacha-api/pom.xml, backend/mr-api-java-server/pom.xml, backend/mr-streaming-api/pom.xml, backend/sse-edge-api/pom.xml, backend/sse-edge-stats-api/pom.xml
And upgrade the Jersey generator to match. e2e passes.
=> Update to latest OpenAPI Maven Plugin

backend/common-web/src/main/java/io/featurehub/jersey/config/CommonConfiguration.java, backend/common-web/src/main/kotlin/io/featurehub/health/CommonFeatureHubFeatures.kt, backend/common-web/src/main/kotlin/io/featurehub/utils/CurrentTime.kt, backend/common-web/src/main/kotlin/io/featurehub/utils/CurrentTimeSource.kt
Adding common utility methods to get current time so it is easy to mock the class and test
=> Add CurrentTime util methods to common web

backend/common-web/src/main/kotlin/io/featurehub/lifecycle/TelemetryFeature.kt
OpenTelemetry has no capability to support mocking any of its internals
including baggage. Only Tracer and OpenTelemetry are really interfaces.
This adds interface support for Baggage so it can be used for extended
e2e testing.
Adjunct to #534
=> Allow for mocking Baggage

backend/composite-common/pom.xml, backend/composite-jersey/pom.xml, backend/composite-logging/pom.xml, backend/composite-parent/pom.xml, backend/tile-java/tile.xml, backend/tile-java8/tile.xml
=> Kotlin version upgrade

admin-frontend/open_admin_app/pubspec.yaml, backend/mr-db-api/src/main/java/io/featurehub/db/api/AuthenticationApi.java, backend/mr-db-sql/src/main/java/io/featurehub/db/services/AuthenticationSqlApi.java, e2e/pubspec.yaml
Adds some kotlin annotations and fixes some Dart dependencies.
=> General cleanup

backend/tile-app-with-ui/tile.xml, backend/tile-app/tile.xml, pipeline/app-master-pipeline/cloudbuild.yaml
Adds support for automatic reading of an extra config file (/etc/app-config/secrets.properties)
=> add support for an extra config file for secrets

admin-frontend/open_admin_app/lib/api/client_api.dart, admin-frontend/open_admin_app/lib/widgets/user/register/register_url_bloc.dart, admin-frontend/open_admin_app/lib/widgets/user/signin/signin_widget.dart, admin-frontend/open_admin_app/lib/widgets/user/update/password_reset_widget.dart
Maybe fixes #554 - could not reproduce that specific issue.
=> Fix the replace temporary password flow

backend/dacha/src/main/java/io/featurehub/dacha/InMemoryCache.java, backend/mr-db-sql/src/main/java/io/featurehub/db/publish/DbCacheSource.java
Based on an issue found while testing. Cannot reproduce the issue but best to be defensive.
=> defensive propagation in dacha

admin-frontend/build-frontend.sh, admin-frontend/build/build.sh, admin-frontend/src/main/resources/pre-build-assembly.xml, backend/build.sh, backend/dacha/src/main/java/io/featurehub/dacha/InMemoryCache.java, backend/edge-common/src/main/kotlin/io/featurehub/edge/rest/FeatureUpdate.kt
- Prevent a request for a non-existent environment from causing an NPE in Dacha
- Prevent an Edge update request from NPEing when no request to update value is provided
=> fix a NPE issue with the move to Kotlin

admin-frontend/open_admin_app/lib/routes/service_env_route.dart
=> Minor tooltip update to say API key  (frontend)

sdks/typescript/featurehub-javascript-client-sdk/README.md, sdks/typescript/featurehub-javascript-client-sdk/package.json
e-tag support in JS Browser SDK - publish version 1.0.9
=> publish version 1.0.9

backend/mr-db-sql/src/main/java/io/featurehub/db/services/EnvironmentSqlApi.java, backend/mr-db-sql/src/main/java/io/featurehub/db/services/FeatureSqlApi.java, backend/mr-db-sql/src/main/java/io/featurehub/db/utils/EnvironmentUtils.java
This wasn't quite right, it had a conceptual issue.
=> Resolve ordering issue of environments in features

admin-frontend/build-frontend.sh, backend/mr-db-sql/pom.xml, backend/mr-publish-api/pom.xml, backend/party-server/pom.xml, pipeline/build/base_party/Dockerfile, pipeline/build/base_party/make-image.sh, pipeline/build/flutter_web/make-image.sh
This upgrades NATS, upgrades the Flutter build to 2.5.3 and other associated dependencies. It has been tested with a full run through.
Fixes #585
=> upgrade NATS, front end

backend/build.sh, backend/mr-db-sql/src/main/java/io/featurehub/db/services/ConvertUtils.java, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureSpec.groovy, backend/push.sh, e2e/lib/user_common.dart, e2e/lib/util.dart, e2e/test/features/service_accounts_load.feature, e2e/test/steps/ApplicationStepdefs.dart, e2e/test/steps/EnvironmentStepdefs.dart, e2e/test/steps/PortfolioStepdefs.dart
Minor updates for 1.5.1 release from testing.
=> Release 1.5.1 changes

backend/common-web/src/main/kotlin/io/featurehub/jersey/FeatureHubJerseyHost.kt, backend/dacha/src/main/kotlin/io/featurehub/dacha/DachaFeature.kt, backend/edge-full/src/main/java/io/featurehub/edge/Application.java, backend/party-server/src/main/kotlin/io.featurehub.party/Application.kt
remove DI hack, go back to using @Immediate
=> Remove di hack

backend/composite-common/pom.xml, backend/composite-logging-api/pom.xml, backend/composite-logging/pom.xml
=> log4j 2.15 upgrade

admin-frontend/open_admin_app/lib/theme/theme_data.dart, admin-frontend/open_admin_app/lib/widgets/common/fh_drawer.dart, admin-frontend/open_admin_app/lib/widgets/features/feature_names_left_panel.dart, admin-frontend/open_admin_app/lib/widgets/features/feature_value_cell.dart, admin-frontend/open_admin_app/lib/widgets/stepper/custom_stepper.dart, admin-frontend/open_admin_app/lib/widgets/stepper/progress_stepper_widget.dart
=> adminui-alignment-fixes

backend/common-db/src/main/kotlin/io/featurehub/app/db/utils/CommonDbFeature.kt, backend/composite-db-drivers/pom.xml, backend/mr-db-ebean/src/main/resources/dbmigration/oracle/1.0__initial.sql, backend/mr-db-ebean/src/test/java/io/featurehub/db/GenerateDbMigration.java
As per request.
Database migrations for Oracle and Oracle JDBC driver.
=> Add base support for Oracle DB

admin-frontend/open_admin_app/lib/theme/theme_data.dart, admin-frontend/open_admin_app/lib/widget_creator.dart, admin-frontend/open_admin_app/lib/widgets/common/external_docs_links_widget.dart, admin-frontend/open_admin_app/lib/widgets/common/fh_appbar.dart, admin-frontend/open_admin_app/lib/widgets/common/fh_portfolio_selector.dart, admin-frontend/open_admin_app/lib/widgets/features/table-collapsed-view/flag_colored_on_off_label.dart
Enhancement in the Admin app to add links to the FH docs and Github
=> Add links to docs in the Admin app

admin-frontend/open_admin_app/lib/utils/utils.dart, admin-frontend/open_admin_app/lib/widget_creator.dart, admin-frontend/open_admin_app/lib/widgets/common/fh_drawer.dart, admin-frontend/open_admin_app/lib/widgets/common/fh_error.dart, admin-frontend/open_admin_app/lib/widgets/common/fh_error_message_details_widget.dart
Admin app error handling refactor of some old code
=> Admin app error handling refactor 

adks/e2e-sdk/app/steps/flag_steps.ts, adks/e2e-sdk/app/steps/setup.ts, adks/e2e-sdk/app/support/hooks.ts, adks/e2e-sdk/app/support/world.ts, backend/dacha/src/main/java/io/featurehub/dacha/InMemoryCache.java, backend/edge-rest/src/main/kotlin/io/featurehub/edge/db/sql/DbDachaSqlApi.kt, backend/mr-db-sql/src/main/java/io/featurehub/db/services/FeatureSqlApi.java, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/publish/DbCacheSource.kt, e2e/lib/superuser_common.dart, e2e/test/features/feature_values.feature, e2e/test/features/persona_acls.feature
Fixes and tests for the following tickets:
Fixes #544
Fixes #639
=> Fix serving rollout strategies in party-server-ish and edge-rest. Fix accessing flags/values when set first time

admin-frontend/open_admin_app/lib/api/client_api.dart, admin-frontend/open_admin_app/lib/api/web_interface/web_url_handler.dart, admin-frontend/open_admin_app/lib/routes/create_user_route.dart, admin-frontend/open_admin_app/lib/widgets/user/create/create_user_bloc.dart, admin-frontend/open_admin_app/lib/widgets/user/list/list_users_widget.dart, backend/common-web/src/main/kotlin/io/featurehub/jersey/AdminAppStaticHttpHandler.kt, backend/common-web/src/main/kotlin/io/featurehub/jersey/DelegatingHandler.kt, backend/common-web/src/main/kotlin/io/featurehub/jersey/FeatureHubJerseyHost.kt, backend/mr-api/mr-api.yaml, backend/mr/src/main/java/io/featurehub/mr/resources/AuthResource.java, backend/mr/src/main/java/io/featurehub/mr/resources/PersonResource.java, backend/party-server/src/test/resources/application.properties, docs/installation.adoc
This allows FeatureHub to run on a non root url in case someone is subhosting it in their domain.
Fixes issue #634
=> Allow for a configurable base path for FeatureHub

backend/common-web/src/main/kotlin/io/featurehub/jersey/AdminAppStaticHttpHandler.kt, e2e/lib/user_common.dart, e2e/lib/util.dart, e2e/test/features/person_group.feature, e2e/test/steps/AdminPersonStepdefs.dart, e2e/test/steps/PersonStepdefs.dart
Minor fixups and changes to registration tests
=> Fixup of registration tests

adks/e2e-sdk/.gitignore, adks/e2e-sdk/package-lock.json, backend/composite-common/pom.xml, backend/composite-parent/pom.xml, backend/tile-java8/tile.xml
This is a hygiene release to update core libraries.
=> [Maint] Upgrade of Kotlin to 1.6.10 and Ebean to 12.14.1

adks/e2e-sdk/app/steps/flag_steps.ts, adks/e2e-sdk/app/steps/general_steps.ts, adks/e2e-sdk/app/steps/nonflag_steps.ts, adks/e2e-sdk/app/steps/setup.ts, adks/e2e-sdk/app/support/discovery.ts, adks/e2e-sdk/app/support/world.ts, adks/e2e-sdk/features/environment.feature, adks/e2e-sdk/features/flags.feature, adks/e2e-sdk/package-lock.json, adks/e2e-sdk/package.json, adks/e2e-sdk/run.sh, backend/edge-full/src/main/java/io/featurehub/edge/StreamingFeatureSource.java, backend/edge-full/src/main/java/io/featurehub/edge/client/TimedBucketClientConnection.java, backend/mr-db-sql/src/main/java/io/featurehub/db/publish/CacheSource.java, backend/mr-db-sql/src/main/java/io/featurehub/db/publish/DummyPublisher.java, backend/mr-db-sql/src/main/java/io/featurehub/db/services/ApplicationSqlApi.java, backend/mr-db-sql/src/main/java/io/featurehub/db/services/DbArchiveStrategy.java, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/publish/DbCacheSource.kt, sdks/typescript/featurehub-javascript-client-sdk/app/client_feature_repository.ts, sdks/typescript/featurehub-javascript-client-sdk/app/feature_state.ts, sdks/typescript/featurehub-javascript-client-sdk/app/feature_state_holders.ts, sdks/typescript/featurehub-javascript-client-sdk/app/middleware.ts, sdks/typescript/featurehub-javascript-client-sdk/package.json, sdks/typescript/featurehub-javascript-client-sdk/test/middleware_spec.ts, sdks/typescript/featurehub-javascript-client-sdk/test/repository_delete_feature_spec.ts, sdks/typescript/featurehub-javascript-client-sdk/test/repository_events_spec.ts, sdks/typescript/featurehub-javascript-client-sdk/test/repository_single_feature_spec.ts, sdks/typescript/featurehub-javascript-node-sdk/package.json
When an environment was deleted, it would not get published
because it failed to push our required fields. This change
ensures this happens and adds in e2e tests to check this
is happening from end-to-end.
Fixes #655
=> [Minor-Bug] Deleted environments not getting published

backend/composite-parent/pom.xml
=> H2 has another critical severity.

admin-frontend/open_admin_app/lib/widgets/user/list/list_users_bloc.dart, admin-frontend/open_admin_app/lib/widgets/user/list/list_users_widget.dart, backend/mr-api/mr-api.yaml, backend/mr-db-api/src/main/java/io/featurehub/db/api/DBLoginSession.java, backend/mr-db-api/src/main/java/io/featurehub/db/api/FillOpts.java, backend/mr-db-api/src/main/java/io/featurehub/db/api/PersonApi.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbLogin.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbPerson.java, backend/mr-db-sql/src/main/java/io/featurehub/db/publish/CacheSource.java, backend/mr-db-sql/src/main/java/io/featurehub/db/services/AuthenticationSqlApi.java, backend/mr-db-sql/src/main/java/io/featurehub/db/services/ConvertUtils.java, backend/mr-db-sql/src/main/java/io/featurehub/db/services/PersonSqlApi.java, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/ServiceAccountSqlApi.kt, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/AuthenticationSpec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/ConvertUtilsSpec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/RolloutStrategyValidationUtilsSpec.groovy, backend/mr/src/main/java/io/featurehub/mr/auth/DatabaseAuthRepository.java, backend/mr/src/main/java/io/featurehub/mr/auth/InMemoryAuthRepository.java, backend/mr/src/main/java/io/featurehub/mr/auth/SessionToken.java, backend/mr/src/main/java/io/featurehub/mr/resources/PersonResource.java, backend/mr/src/test/groovy/io/featurehub/mr/rest/PersonResourceSpec.groovy
Surfaces when the user last logged in into the UI.
Fixes #662
=> Person last logged in

backend/common-db/src/main/kotlin/io/featurehub/app/db/utils/CommonDbFeature.kt, backend/common-db/src/main/kotlin/io/featurehub/app/db/utils/FeatureHubChangeLog.kt, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbAcl.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbApplication.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbApplicationFeature.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbEnvironment.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbFeatureValue.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbGroup.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbLogin.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbNamedCache.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbOrganization.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbPerson.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbPortfolio.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbRolloutStrategy.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbServiceAccount.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbServiceAccountEnvironment.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbStrategyForFeatureValue.java, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbUserState.java, backend/party-server/src/test/resources/log4j2-test.xml
Allows special log to output all changes happening to the system.
Fixes #644
=> [Feature] Enable Changelog tracking

backend/dacha-api/dacha-api.yaml, backend/dacha/src/main/java/io/featurehub/dacha/EnvironmentFeatures.java, backend/dacha/src/main/java/io/featurehub/dacha/InMemoryCache.java, backend/dacha/src/test/groovy/io/featurehub/dacha/MultiCacheSpec.groovy, backend/dacha/src/test/java/io/featurehub/dacha/Dacha2AppRunner.java, backend/dacha/src/test/java/io/featurehub/dacha/Dacha3AppRunner.java, backend/dacha/src/test/java/io/featurehub/dacha/MrInMemoryCache.java, backend/dacha/src/test/resources/application.properties, backend/dacha/src/test/resources/application2.properties, backend/dacha/src/test/resources/application3.properties, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/publish/DbCacheSource.kt
As new Dachas come online, they get bad copies of the environments. This
fixes that issue.
Fixes #671
=> [Bug] Dacha losing feature changes as multiple copies are cycled through

backend/mr-db-ebean/src/main/resources/dbmigration/h2/1.11.sql, backend/mr-db-ebean/src/main/resources/dbmigration/model/1.11.model.xml, backend/mr-db-ebean/src/main/resources/dbmigration/mysql/1.11.sql, backend/mr-db-ebean/src/main/resources/dbmigration/oracle/1.11.sql, backend/mr-db-ebean/src/main/resources/dbmigration/postgres/1.11.sql, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbFeatureValue.java, backend/mr-db-sql/src/main/java/io/featurehub/db/listener/FeatureUpdateListener.java, backend/mr-db-sql/src/main/java/io/featurehub/db/services/FeatureSqlApi.java
This fixes the issue by creating an index and ensuring that the listener
is a queue instead of a topic subscriber.
Fixes #678
=> [Bug] Resolve issue with test API creating duplicate feature values

sdks/typescript/featurehub-javascript-client-sdk/README.md, sdks/typescript/featurehub-javascript-client-sdk/mocharc.yml, sdks/typescript/featurehub-javascript-client-sdk/package.json
Updates to the typescript SDK documentation for the 1.0.11 release
=> [Docs] Typescript SDK Documentation updates

api_bucket/.gitignore, infra/api-bucket/.gitignore, infra/api-bucket/Pulumi.api.yaml, infra/api-bucket/Pulumi.yaml, infra/api-bucket/index.ts, infra/api-bucket/package-lock.json, infra/api-bucket/package.json, infra/api-bucket/tsconfig.json
Added a new GCP storage bucket. This will serve our OpenAPI docs. GitHub actions pipeline to come which will automatically publish these.
=> Add GCP storage bucket to serve OpenAPI docs out of

admin-frontend/open_admin_app/lib/api/client_api.dart, admin-frontend/open_admin_app/lib/api/router.dart, admin-frontend/open_admin_app/lib/config/route_handlers.dart, admin-frontend/open_admin_app/lib/config/routes.dart, admin-frontend/open_admin_app/lib/routes/fh_navigator.dart, admin-frontend/open_admin_app/lib/routes/not_found_route.dart, admin-frontend/open_admin_app/lib/routes/oauth2_fail_route.dart, backend/mr-db-api/src/main/java/io/featurehub/db/api/AuthenticationApi.java, backend/mr-db-sql/src/main/java/io/featurehub/db/services/AuthenticationSqlApi.java, backend/mr/src/main/java/io/featurehub/mr/resources/oauth2/OAuth2MRAdapter.java, backend/security-oauth/src/main/kotlin/io/featurehub/web/security/oauth/OauthResource.kt
fixes https://github.com/featurehub-io/featurehub/issues/452 and https://github.com/featurehub-io/featurehub/issues/698
=> When OAuth2 login fails, the server should route to a nice page on the front end explaining what happened

backend/mr-db-sql/src/main/java/io/featurehub/db/services/GroupSqlApi.java
Allows overriding of key features in GroupSql
=> [Internal] minor update to allow overriding group-sql

backend/mr-db-api/src/main/java/io/featurehub/db/api/AuthenticationApi.java, backend/mr-db-sql/src/main/java/io/featurehub/db/services/AuthenticationSqlApi.java, backend/mr/src/main/java/io/featurehub/mr/resources/oauth2/OAuth2MRAdapter.java
This ensures that deleted users cannot login.
Fixes #702
=> Deleted users were allowed in by oauth

backend/mr-db-sql/src/main/java/io/featurehub/db/services/ConvertUtils.java, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/EnvironmentSqlApi.kt, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Environment2Spec.groovy
There are some issues that have been identified around environment ordering and deleting environments in their orders.
=> [Fix] Environment ordering issues

backend/common-web/src/main/kotlin/io/featurehub/rest/CorsFilter.kt, backend/common-web/src/test/groovy/io/featurehub/rest/CorsFilterSpec.groovy, backend/edge-api/sse-api.yaml, backend/edge-common/src/main/kotlin/io/featurehub/edge/features/EtagHolder.kt, backend/edge-common/src/main/kotlin/io/featurehub/edge/rest/FeatureGet.kt, backend/edge-common/src/test/groovy/io/featurehub/edge/features/EtagSplitterSpec.groovy, backend/party-server/src/test/resources/application.properties, backend/party-server/src/test/resources/log4j2-test.xml
This is refining work on the etag and Edge cache.
=> Update how the Edge cache works

admin-frontend/open_admin_app/lib/widgets/apps/group_permissions_widget.dart, admin-frontend/open_admin_app/lib/widgets/apps/service_account_permissions_widget.dart
=> Feature: Add Change value/ retire permission to display in the Admin UI

backend/composite-db-drivers/pom.xml, backend/mr-db-ebean/pom.xml
There was an alert on Postgres, so this is taking the opportunity
to update them all.
=> [Internal] Update all database drivers

backend/build.sh, backend/dacha/src/main/java/io/featurehub/dacha/ServerConfig.java, backend/party-server/pom.xml, backend/release.sh, backend/tile-app-with-ui/tile.xml, backend/tile-app/tile.xml, pipeline/build/base_party/Dockerfile, pipeline/build/base_party/make-image.sh
This changes the default process of building so that a new base image is
used that has multiple architectures, and our image building supports them.
Fixes: https://github.com/featurehub-io/featurehub-install/issues/31
@wgarnes this is the branch that gives us multi-architecture builds.
=> [feature] Support multi-architecture builds

admin-frontend/open_admin_app/lib/api/client_api.dart, admin-frontend/open_admin_app/lib/common/stream_valley.dart, admin-frontend/open_admin_app/lib/config/route_handlers.dart, admin-frontend/open_admin_app/lib/routes/apps_route.dart, admin-frontend/open_admin_app/lib/routes/features_overview_route.dart, admin-frontend/open_admin_app/lib/routes/manage_app_route.dart, admin-frontend/open_admin_app/lib/routes/manage_group_route.dart, admin-frontend/open_admin_app/lib/routes/manage_service_accounts_route.dart, admin-frontend/open_admin_app/lib/widgets/apps/manage_app_bloc.dart, admin-frontend/open_admin_app/lib/widgets/apps/service_account_list_widget.dart, admin-frontend/open_admin_app/lib/widgets/common/external_docs_links_widget.dart, admin-frontend/open_admin_app/lib/widgets/common/fh_appbar.dart, admin-frontend/open_admin_app/lib/widgets/common/fh_scaffold.dart, admin-frontend/open_admin_app/lib/widgets/environments/env_list_widget.dart, admin-frontend/open_admin_app/lib/widgets/features/create_update_feature_dialog_widget.dart, admin-frontend/open_admin_app/lib/widgets/setup/page3_widget.dart, admin-frontend/open_admin_app/lib/widgets/stepper/progress_stepper_widget.dart
The Rocket Quick Start needs some care and attention.
=> [internal] fixing the initial setup and use of the Rocket quick-start

docs/antora-playbook.yml, docs/antora.yml, docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/pages/installation.adoc
Updates documentation to the 1.5.7-RC branch and adds in 1.5.7 specific documentation.
=> Release 1.5.7 docs

readme.adoc
=> readme broken link fix

backend/composite-db-drivers/pom.xml
The database drivers for gcloud have made some changes and updated their dependencies.
=> [internal] Update the db drivers for gcloud

backend/edge-common/src/main/kotlin/io/featurehub/edge/rest/FeatureUpdate.kt, backend/mr-db-sql/src/main/java/io/featurehub/db/listener/FeatureUpdateListener.java, backend/mr-db-sql/src/main/java/io/featurehub/db/publish/MRPublishModule.java, backend/mr-db-sql/src/main/java/io/featurehub/db/publish/NATSPublisher.java, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/publish/FeatureUpdateListenerSource.kt
When Edge updates come in from API Keys, this allows a more adaptable
process for applying those updates
=> [internal] Internal refinement of feature update listener

admin-frontend/open_admin_app/lib/routes/create_user_route.dart, admin-frontend/open_admin_app/lib/widgets/common/fh_appbar.dart, admin-frontend/open_admin_app/lib/widgets/common/fh_person_avatar.dart, admin-frontend/open_admin_app/lib/widgets/user/common/admin_checkbox.dart, admin-frontend/open_admin_app/lib/widgets/user/signin/signin_widget.dart
=> Fix AppBar responsiveness 

backend/mr-db-sql/src/main/java/io/featurehub/db/services/GroupSqlApi.java, backend/mr-db-sql/src/main/java/io/featurehub/db/utils/ApiToSqlApiBinder.java, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/InternalGroupSqlApi.kt, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/PersonSqlApi.kt, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/ApplicationSpec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/AuthenticationSpec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/ConvertUtilsSpec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Environment2Spec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureSpec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/GroupSpec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Person2Spec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/PersonSpec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/ServiceAccount2Spec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/UserStateSpec.groovy
when a person is added or removed from a superuser, they
don't have the other portfolio admin groups added or removed
from them.
=> internal/superuser-fix - fix propagation of superuser groups

backend/composite-test/pom.xml, pipeline/app-build-pipeline/cloudbuild.yaml
=> Cloud Build PR

pipeline/app-build-pipeline/cloudbuild.yaml, pipeline/build/flutter_web/Dockerfile, pipeline/build/flutter_web/make-image.sh
Upgrades the basic flutter build to 2.10.5
=> [internal] flutter upgrade to 2.10.5

.github/dependabot.yml, backend/composite-common/pom.xml, backend/composite-db-drivers/pom.xml, backend/composite-jersey/pom.xml, backend/composite-parent/pom.xml, backend/edge-full/src/test/groovy/io/featurehub/edge/bucket/EventOutputBucketServiceSpec.groovy, backend/mr-db-ebean/src/main/resources/dbmigration/model/1.15.model.xml, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbPerson.java
Also minor model change in case of future databases and adding
in an experimental dependabot config.
=> [internal/dependency-updates] Security dependency updates

backend/composite-jersey/pom.xml, backend/mr/src/main/java/io/featurehub/mr/resources/oauth2/OAuth2MRAdapter.java, backend/security-common/src/main/kotlin/io/featurehub/web/security/oauth/SSOCompletionListener.kt, backend/security-oauth/src/main/kotlin/io/featurehub/web/security/oauth/OauthResource.kt, backend/security-saml/src/main/kotlin/io/featurehub/web/security/saml/EnvironmentalSamlServiceProviderConfig.kt, backend/security-saml/src/main/kotlin/io/featurehub/web/security/saml/SamlResource.kt, backend/security-saml/src/main/kotlin/io/featurehub/web/security/saml/SamlServiceProviderConfig.kt, backend/security-saml/src/test/groovy/io/featurehub/web/security/saml/EnvironmentalSamlSourcesSpec.groovy, backend/security-saml/src/test/groovy/io/featurehub/web/security/saml/SamlResourceSpec.groovy, docs/modules/ROOT/pages/identity.adoc
Slightly better ways to do a few things.
=> [internal/saml-fixups] A bunch of minor changes to the SAML functionality

admin-frontend/app_mr_layer/pom.xml, admin-frontend/open_admin_app/lib/widgets/features/per_application_features_bloc.dart, admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/strategies/add_attribute_strategy_widget.dart, admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/strategies/multiselect_dropdown.dart, admin-frontend/open_admin_app/lib/widgets/user/common/select_portfolio_group_bloc.dart
The internal coding relied on the OpenAPI generator detecting an serialisation time
that the data type was not a string but a Dart enum and converting it. This isn't a
valid value and  this change fixes that issue.
=> [internal/fix-openapi-upgrade] - Fixing longstanding internal inconsistency

admin-frontend/open_admin_app/lib/routes/manage_app_route.dart, admin-frontend/open_admin_app/lib/theme/theme_data.dart
monor UI fixes for responsiveness
=> internal-ui-fixes

backend/common-web/src/main/kotlin/io/featurehub/jersey/FeatureHubJerseyHost.kt, backend/common-web/src/main/kotlin/io/featurehub/rest/CacheControlFilter.kt, backend/dacha/src/main/java/io/featurehub/dacha/InternalCache.java, backend/dacha/src/main/java/io/featurehub/dacha/ServerConfig.java, backend/dacha/src/main/kotlin/io/featurehub/dacha/CacheUpdateListener.kt, backend/dacha/src/main/kotlin/io/featurehub/dacha/DachaFeature.kt, backend/dacha/src/main/kotlin/io/featurehub/dacha/caching/FastlyPublisher.kt, backend/edge-api/sse-api.yaml, backend/edge-common/src/main/kotlin/io/featurehub/edge/rest/FeatureGet.kt, docs/modules/ROOT/pages/capabilities-table.adoc
This is phase 1 in support for GET. It works for client evaluated
caches, but server evaluated ones will need better support.
=> [feature/fastly-cache] Support a Fastly Cache on GET requests

admin-frontend/open_admin_app/lib/api/client_api.dart, admin-frontend/open_admin_app/lib/common/person_state.dart, admin-frontend/open_admin_app/lib/common/stream_valley.dart, admin-frontend/open_admin_app/lib/config/routes.dart, admin-frontend/open_admin_app/lib/routes/fh_navigator.dart, admin-frontend/open_admin_app/lib/widgets/portfolio/portfolio_bloc.dart, admin-frontend/open_admin_app/lib/widgets/user/list/list_users_bloc.dart
Support for refreshing global screens if/when necessary
=> [internal/global-refresh] - support refreshing global screens

docs/modules/ROOT/pages/sdks-development.adoc
Provide extra information on updates to the SDKs required by recent changes in Edge.
=> [internal/docs] SDK docs update

admin-frontend/open_admin_app/lib/common/person_state.dart, admin-frontend/open_admin_app/lib/utils/utils.dart, admin-frontend/open_admin_app/lib/widgets/common/fh_json_editor.dart, admin-frontend/open_admin_app/lib/widgets/features/set_feature_metadata.dart, admin-frontend/open_admin_app/lib/widgets/features/table-expanded-view/json/edit_json_value_container.dart
Adds additional functionality for #833
=> add ability to add metadata as simple string

admin-frontend/build-frontend.sh, admin-frontend/open_admin_app/lib/routes/features_overview_route.dart, admin-frontend/open_admin_app/lib/routes/manage_app_route.dart, admin-frontend/open_admin_app/lib/routes/manage_group_route.dart, admin-frontend/open_admin_app/lib/routes/manage_service_accounts_route.dart, admin-frontend/open_admin_app/lib/routes/service_env_route.dart, admin-frontend/open_admin_app/lib/theme/theme_data.dart, admin-frontend/open_admin_app/lib/widgets/admin_sdk_service_account/list_admin_service_accounts_widget.dart, admin-frontend/open_admin_app/lib/widgets/apps/group_permissions_widget.dart, admin-frontend/open_admin_app/lib/widgets/apps/service_account_list_widget.dart, admin-frontend/open_admin_app/lib/widgets/apps/service_account_permissions_widget.dart, admin-frontend/open_admin_app/lib/widgets/common/fh_header.dart, admin-frontend/open_admin_app/lib/widgets/environments/env_list_widget.dart, admin-frontend/open_admin_app/lib/widgets/features/feature_names_left_panel.dart, admin-frontend/open_admin_app/lib/widgets/features/features_overview_table_widget.dart, admin-frontend/open_admin_app/lib/widgets/user/list/list_users_widget.dart, pipeline/app-build-pipeline/cloudbuild.yaml, pipeline/build/flutter_web/make-image.sh
So UI elements were not selectable so user is unable to copy and paste, e.g. names of the features. Applied the fix in various text components.
=> UI - make selectable text 

admin-frontend/open_admin_app/lib/widgets/apps/service_account_list_widget.dart
=> fix service account widget error

backend/dacha/src/main/kotlin/io/featurehub/dacha/DachaFeature.kt, backend/dacha2/src/main/kotlin/io/featurehub/dacha2/Dacha2CacheImpl.kt, backend/dacha2/src/main/kotlin/io/featurehub/dacha2/Dacha2CacheListener.kt, backend/dacha2/src/main/kotlin/io/featurehub/dacha2/Dacha2CloudEventListenerImpl.kt, backend/dacha2/src/main/kotlin/io/featurehub/dacha2/Dacha2Feature.kt, backend/dacha2/src/main/kotlin/io/featurehub/dacha2/caching/FastlyPublisher.kt, backend/dacha2/src/test/groovy/io/featurehub/dacha2/Dacha2CloudEventListenerImplSpec.groovy, docs/modules/ROOT/pages/configuration.adoc
- Remove unnecessary code from dacha2,
- cleanup fastly in dacha1,
- enable fastly support in dacha2
- add missing global config for kinesis
=> [internal/fastly-kinesis] Fastly Dacha2 support & Kinesis doc updates

adks/e2e-sdk/app/support/logging.ts, backend/edge-full/src/main/java/io/featurehub/edge/rest/EventStreamResource.java, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/EnvironmentSqlApi.kt, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/PersonSqlApi.kt, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/ServiceAccountSqlApi.kt, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/AdminServiceAccount1Spec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/AdminServiceAccount2Spec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Environment2Spec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureSpec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/Person2Spec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/ServiceAccount2Spec.groovy, backend/mr-eventing/src/main/kotlin/io/featurehub/db/publish/DbCacheSource.kt, backend/mr/src/test/resources/log4j2-test.xml, backend/party-server/src/test/resources/application.properties
Under a very specific circumstance, a race condition can occur which causes the first set value of a non-boolean flat to not get published.
Fixes #870
=> [bugfix/random-missed-update] Non-boolean skipped update for 1st "not set"

backend/mr/src/test/groovy/io/featurehub/mr/rest/GroupResourceSpec.groovy
=> [internal/perms-feature-create] Fix for test failure

docs/modules/ROOT/pages/architecture.adoc, docs/modules/ROOT/pages/capabilities-table.adoc, docs/modules/ROOT/pages/index.adoc
Documentation update for Fastly.
Fixes #874
=> [feature/fastly-documentation] Support for Fastly

backend/common-web/pom.xml, backend/composite-app/pom.xml, backend/composite-common/pom.xml, backend/composite-db-drivers/pom.xml, backend/composite-ebean/pom.xml, backend/composite-jackson/pom.xml, backend/composite-jersey/pom.xml, backend/composite-logging-api/pom.xml, backend/composite-logging/pom.xml, backend/composite-parent/pom.xml, backend/composite-test/pom.xml, backend/tile-java/tile.xml, e2e/pubspec.yaml
This is busy work ready for Java 19, but it brings all our dependencies up to date.
=> [internal/upgrade-dependencies] 3rd party dependency update

backend/composite-jersey/pom.xml, backend/eventing-google-pubsub/src/main/kotlin/io/featurehub/events/pubsub/PubSubFactoryService.kt, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/EnvironmentSqlApi.kt, e2e/lib/util.dart
Fixups for 1.5.10 based on testing.
=> [internal/release-1.5.10-fixes] Thorough e2e tests fixups

adks/e2e-sdk/app/steps/nonflag_steps.ts, backend/mr-db-models/src/main/java/io/featurehub/db/model/DbFeatureValueVersion.java, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingRetiredUnitSpec.groovy
Minor auditing fixes for edge cases.
=> [internal/minor-historical-fix] Fixes for auditing

admin-frontend/open_admin_app/lib/widgets/apps/manage_app_bloc.dart, admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/lock_unlock_switch.dart, admin-frontend/open_admin_app/lib/widgets/features/edit-feature/feature_cell_holder.dart
=> UI dashboard - add tooltip to the feature name

backend/dacha2/src/main/kotlin/io/featurehub/dacha2/pubsub/PubsubDachaCloudEvents.kt, backend/webhook-api/webhook-messages.yaml, backend/webhook-feature-update/src/main/kotlin/io/features/webhooks/features/WebhookFeature.kt, docs/modules/ROOT/pages/webhooks-configuration.adoc
Minor changes around Google PubSub use of Webhooks.
=> [internal/webhook-updates] Minor updates around pubsub webhooks

backend/dacha2/src/main/kotlin/io/featurehub/dacha2/Dacha2CacheImpl.kt, backend/dacha2/src/main/kotlin/io/featurehub/dacha2/FeatureValuesFactory.kt
extra internal logging for dacha2
=> minor change to fastly

.github/workflows/saas-update.yaml
=> Allow triggering of workflow on SaaS Codebase

admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/add_attribute_strategy_widget.dart
=> Ability to add multi comma separated values in the strategies field 

backend/composite-jersey/pom.xml, docs/modules/ROOT/pages/metrics.adoc
=> Allow for the disabling of prometheus metrics

admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/edit_feature_value_widget.dart, admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/custom_strategy_bloc.dart, admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/strategy_card_widget.dart, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingStrategiesUnitSpec.groovy
=> [feature/reordering-strategies] Support reordering strategies

admin-frontend/open_admin_app/lib/widgets/common/fh_alert_dialog.dart, admin-frontend/open_admin_app/lib/widgets/common/fh_error.dart, admin-frontend/open_admin_app/lib/widgets/common/fh_scaffold.dart
Almost all dialogs, the ESC key now closes them as standard behaviour.
Fixes #955
=> [internal/esc-key] Add ESC key to all relevant dialogs

backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingBaseUnitSpec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingStrategiesUnitSpec.groovy, docs/modules/ROOT/pages/sdks-development.adoc
This deals with a few permission used cases that leaked through.
=> Strategy permissions checks

admin-frontend/open_admin_app/lib/routes/edit_user_route.dart, admin-frontend/open_admin_app/lib/widgets/user/edit/edit_user_bloc.dart
The edit dialog wasn't waiting until the save completed before redirecting the user to the list users page
Fixes #951
=> [bugfix/update-person] Person's details not updated after edit

backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureSpec.groovy
Auditing should always be enabled, all future functionality relies on it.
=> [feature/auditing] Always enabled Auditing

backend/mr-db-api/src/main/java/io/featurehub/db/api/PersonFeaturePermission.java
Change Value is not a create feature
=> [internal/fix] Remove permission for create feature

admin-frontend/open_admin_app/lib/widgets/apps/group_permissions_widget.dart, admin-frontend/open_admin_app/lib/widgets/features/edit-feature/set_feature_metadata.dart
Didn't respect if permission was not granted to edit Feature level settings
=> fix metadata editing permission

infra/api-bucket/index.ts
Create new bucket that will a single level domain name under GCP API so we can put fastly in front of it.
=> New API docs bucket

backend/composite-common/pom.xml, backend/composite-jersey/pom.xml, backend/mr-db-ebean/src/main/resources/ebean.mf
jakarta.xml.bind + impl needs to be a core dependency now.
=> [internal/minor-dep-fixes] More minor dependency fixes

docs/modules/ROOT/pages/capabilities-table.adoc
Details about the Swift SDK and updates to the capabilities.
=> Swift SDK + updates to details of SDKs

backend/dacha/src/main/java/io/featurehub/dacha/EnvironmentFeatures.java, backend/dacha/src/main/java/io/featurehub/dacha/InMemoryCache.java, backend/dacha/src/main/kotlin/io/featurehub/dacha/DachaFeature.kt, backend/dacha/src/main/kotlin/io/featurehub/dacha/InternalCache.kt, backend/dacha/src/main/kotlin/io/featurehub/dacha/resource/PublishCacheResource.kt, backend/dacha/src/main/resources/deploy-defaults/log4j2.xml, backend/dacha/src/test/groovy/io/featurehub/dacha/InternalMemoryCacheSpec.groovy, backend/dacha/src/test/java/io/featurehub/dacha/Dacha2AppRunner.java, backend/dacha/src/test/java/io/featurehub/dacha/Dacha3AppRunner.java, backend/dacha/src/test/java/io/featurehub/dacha/MrInMemoryCache.java, backend/dacha/src/test/resources/log4j2-test.xml, backend/dacha2/src/main/kotlin/io/featurehub/dacha2/FeatureValuesFactory.kt, backend/edge-full/src/test/resources/application.properties, backend/eventing-nats/src/main/kotlin/io/featurehub/publish/NATSConnectionSource.kt
Some work around robustness for Dacha1.
=> Dacha1 robustness checking

adks/e2e-sdk/README.adoc, adks/e2e-sdk/app/steps/setup.ts, adks/e2e-sdk/app/steps/webhook_steps.ts, adks/e2e-sdk/app/support/discovery.ts, adks/e2e-sdk/app/support/make_me_a_webserver.ts, adks/e2e-sdk/app/support/world.ts, adks/e2e-sdk/features/examples.feature
Modifies and documents how to do remote hosted testing.
=> [internal/allow-testing-with-adk] Remote hosted testing

.github/workflows/adocs-build.yml, backend/mr-db-api/src/main/kotlin/io/featurehub/db/api/FeatureApi.kt, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingRetiredUnitSpec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingStrategiesUnitSpec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingValueUnitSpec.groovy, backend/mr/src/main/java/io/featurehub/mr/resources/FeatureResource.java
If you unlocked, changed and locked again in the UI and tried to save, you should get a Lock failure from  the backend. But it should be a 400 error not a 500.
=> [internal/locked-issue] error not surfacing properly for lock errors

admin-frontend/build-frontend.sh, admin-frontend/build/build.sh, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt
Picked up that an unchanged feature value was trying to insert a new record.
=> [internal/auditing-fix] Auditing fixes

backend/common-web/src/main/kotlin/io/featurehub/info/ApplicationVersionDiscovery.kt, backend/edge-stats-emitter/pom.xml
The party server and edge server would not report their versions correctly.
=> [bugfix/version-api-fix] Not reporting version correctly

backend/eventing-kinesis/testing-setup.sh, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureAuditingStrategiesUnitSpec.groovy, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureUpdatesPublishingSpec.groovy, backend/mr-eventing/pom.xml, backend/mr-eventing/src/main/kotlin/io/featurehub/mr/events/EventingFeature.kt, backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/FeatureMessagingMetrics.kt, backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/MessagingConfig.kt, backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/MessagingFeature.kt, backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/converter/FeatureMessagingConverterImpl.kt, backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/publisher/kinesis/KinesisFeatureMessagingPublisher.kt, backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/publisher/nats/NatsFeatureMessagingPublisher.kt, backend/mr-messaging-processor/src/main/kotlin/io/featurehub/messaging/publisher/pubsub/PubsubFeatureMessagingPublisher.kt, backend/mr/src/main/kotlin/io/featurehub/mr/ManagementRepositoryFeature.kt
Publishers added for nats, pubsub and kinesis
- [x ] New feature (non-breaking change which adds functionality)
Tested feature messaging updates are published to nats channel by running local nats server, verified messages published to kinesis stream using localstack and pubsub channel using docker pubsub container
=> [Slack/Teams integration] Add publishers to publish feature messaging updates

adks/e2e-sdk/app/steps/webhook_steps.ts, adks/e2e-sdk/features/webhooks.feature, adks/e2e-sdk/package-lock.json, backend/dacha2/pom.xml, backend/edge-full/pom.xml
Internal update of Guava and more comprehensive Webhook expectation test.
=> [Internal/update guava] Internal dependency and test updates

backend/edge-common/src/main/kotlin/io/featurehub/edge/features/FeatureRequestCollection.kt
Edge can come up before Dacha is available and needs to respond with a signal to the SDK client to indicate that it needs to "come back later".
Fixes #1024
=> [bugfix/dacha-not-available] Fix issue if dacha is not available

admin-frontend/open_admin_app/lib/config/route_handlers.dart, admin-frontend/open_admin_app/lib/routes/edit_user_route.dart, admin-frontend/open_admin_app/lib/widget_creator.dart, admin-frontend/open_admin_app/lib/widgets/user/common/admin_checkbox.dart, admin-frontend/open_admin_app/lib/widgets/user/edit/edit_user_bloc.dart
=> Billing admin

admin-frontend/open_admin_app/lib/routes/create_admin_service_accounts_route.dart, admin-frontend/open_admin_app/lib/routes/edit_admin_service_account_route.dart
Allow admin service accounts to be super-admins.
Fixes #1049
=> [feature/super-admin] Allow service accounts to be super-admins via UI

adks/e2e-sdk/app/steps/flag_steps.ts, adks/e2e-sdk/app/steps/general_steps.ts, adks/e2e-sdk/app/steps/nonflag_steps.ts, adks/e2e-sdk/app/steps/strategies.ts, adks/e2e-sdk/app/support/world.ts, adks/e2e-sdk/features/flags.feature, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureSqlApi.kt
Ensures that if a feature is locked, it should not be allowed to be changed.
Fixes #1051
=> [bugfix/locked-features] Locked features not rejecting subtle changes

backend/common-web/src/main/java/io/featurehub/jersey/config/LocalExceptionMapper.java, backend/common-web/src/main/kotlin/io/featurehub/lifecycle/TelemetryFeature.kt, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureGroupSqlApi.kt, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureGroupSpec.groovy, backend/mr-eventing/src/main/kotlin/io/featurehub/mr/events/EventingFeature.kt, backend/party-server-ish/src/test/resources/application.properties
- for party-server-ish for publishing
- dialing down exception noise for non-404s
- making sure exceptions log the url that are being used to call them
- fix for feature groups
=> [bugfix/various] bug fixes

backend/security-saml/pom.xml
=> [internal/security-sampl] dependency update for SAML

admin-frontend/open_admin_app/lib/widgets/setup/setup_bloc.dart, backend/mr-api/mr-api.yaml, backend/mr/src/main/kotlin/io/featurehub/mr/resources/SetupResource.kt, infra/api-bucket/files/mrapi/1.2.0.yaml
On initial setup, the capabilities are missing so Feature groups and Webhooks do not appear until refresh.
=> [bugfix/initial-setup] Fixes missing capabilities in front end

admin-frontend/open_admin_app/lib/widgets/apps/webhook/slack_panel_widget.dart, backend/encryption-common/src/main/kotlin/io.featurehub.encryption/WebhookEncryptionService.kt, backend/mr/src/main/kotlin/io/featurehub/mr/resources/WebhookResource.kt, backend/party-server/src/test/resources/application.properties, backend/webhook-feature-update/sinatra-example/webhook_app.rb, backend/webhook-feature-update/src/main/kotlin/io/features/webhooks/features/WebhookFeature.kt
UI fixes for Slack and data fixes for encrypted info for Webhooks.
=> agreed fixes for slack

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/resilience.adoc, docs/run.sh
Docs updates - resilience, backup feature flags
=> Add resilience doc

admin-frontend/open_admin_app/lib/widgets/apps/webhook/slack_panel_widget.dart, admin-frontend/open_admin_app/lib/widgets/apps/webhook/webhook_configuration_widget.dart, admin-frontend/open_admin_app/lib/widgets/apps/webhook/webhook_environment_widget.dart
Plus various fixes for Slack integration page
=> Fix for #1115 - webhook url to allow https

admin-frontend/open_admin_app/lib/widgets/apps/service_account_permissions_widget.dart
New sdk feature properties raised a new issue.
=> [internal] minor bugfixes for UI related issues

backend/common-web/pom.xml, backend/common-web/src/main/kotlin/io/featurehub/lifecycle/TelemetryFeature.kt, backend/mr-messaging-channel/src/main/kotlin/io/featurehub/messaging/MessagingPublishingFeature.kt
OTEL support for Zipkin and Jaeger exporters, finesses on auto-configuration.
=> [feature] Support for Zipkin & Jaeger exporters

admin-frontend/open_admin_app/lib/theme/theme_data.dart, admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/edit_feature_value_widget.dart, admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/strategies/fv_strategy_editor_provider.dart, admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/valueeditors/edit_boolean_value_dropdown_widget.dart, admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/valueeditors/edit_json_value_container.dart, admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/valueeditors/edit_number_value_container.dart, admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/valueeditors/edit_string_value_container.dart, admin-frontend/open_admin_app/lib/widgets/features/editing_feature_value_block.dart, admin-frontend/open_admin_app/lib/widgets/strategyeditor/strategy_editing_widget.dart, docs/modules/ROOT/pages/users.adoc
Currently, when operating with features dashboard, sometimes it is not very clear if updates were made by a user and they have to press "Save" button. This change will help with better user experience by introducing a clear message and make it visible enough so user knows that they made changes and need to press Save. 
=> Admin UI - Add a prompt/snackbar when feature value or its strategy changes

admin-frontend/open_admin_app/lib/widgets/strategyeditor/add_attribute_strategy_widget.dart, admin-frontend/open_admin_app/lib/widgets/strategyeditor/matchers.dart, admin-frontend/open_admin_app/lib/widgets/strategyeditor/transform_strategy_conditions.dart
add strategy attribute conditions - Includes and Excludes to Platform, Device and Country types
=> Fix #1141 add strategy attribute conditions - Includes and Excludes to Platform, Device and Country types

admin-frontend/open_admin_app/lib/widgets/features/cell-view/value_cell.dart, admin-frontend/open_admin_app/lib/widgets/features/edit-feature-value/edit_feature_value_widget.dart, admin-frontend/open_admin_app/lib/widgets/features/editing_feature_value_block.dart, admin-frontend/open_admin_app/pubspec.yaml, backend/mr-api/mr-api.yaml, backend/mr-db-sql/src/main/kotlin/io/featurehub/db/services/FeatureHistorySqlApi.kt, backend/mr-db-sql/src/test/groovy/io/featurehub/db/services/FeatureHistorySpec.groovy, infra/api-bucket/files/mrapi/1.2.1.yaml
=> Add feature auditing history

backend/common-web/src/main/kotlin/io/featurehub/jersey/FeatureHubJerseyHost.kt
A url could be such that it would cause an error to be logged back to the user by Grizzly, the web server we use. This prevents any information leakage but still logs the error.
=> [fix] set default error page for grizzly web server

backend/edge-full/src/test/resources/application.properties, backend/mr/src/main/resources/deploy-defaults/common.properties, backend/mr/src/test/resources/application.properties, backend/party-server/src/main/resources/deploy-defaults/common.properties, backend/party-server/src/test/resources/application.properties
Force the user to set one rather than inherit the default one.
=> [chore] remove default password for encryption
